-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\EkalmanF_ac_sim\EKF.vhd
-- Created: 2026-01-12 14:16:47
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.02
-- Target subsystem base rate: 0.02
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.02
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- y_k_k                         ce_out        0.02
-- u                             ce_out        0.02
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: EKF
-- Source Path: EkalmanF_ac_sim/EKF
-- Hierarchy Level: 0
-- Model version: 1.76
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.EKF_pkg.ALL;

ENTITY EKF IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
        In2                               :   IN    vector_of_std_logic_vector32(0 TO 1);  -- sfix32_En20 [2]
        E                                 :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        y_k_k                             :   OUT   vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
        u                                 :   OUT   vector_of_std_logic_vector32(0 TO 3)  -- sfix32_En20 [4]
        );
END EKF;


ARCHITECTURE rtl OF EKF IS

  -- Component Declarations
  COMPONENT Kalman_Gain_Calculation
    PORT( P_k_k_1                         :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          H                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          C                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T1                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T2                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T3                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T4                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T5                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T6                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T7                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T8                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T9                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T10                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T11                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T12                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T13                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T14                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T15                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T16                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          K_k                             :   OUT   matrix_of_std_logic_vector32(0 TO 3, 0 TO 3)  -- sfix32_En20 [4x4]
          );
  END COMPONENT;

  COMPONENT Innovation
    PORT( x_k_k_1                         :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
          z_k                             :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
          H                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          y_k                             :   OUT   vector_of_std_logic_vector32(0 TO 3)  -- sfix32_En20 [4]
          );
  END COMPONENT;

  COMPONENT MATLAB_Function_block
    PORT( xkk                             :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
          Jacobs                          :   OUT   matrix_of_std_logic_vector32(0 TO 3, 0 TO 3)  -- sfix32_En20 [4x4]
          );
  END COMPONENT;

  COMPONENT Predict
    PORT( u_k                             :   IN    vector_of_std_logic_vector32(0 TO 1);  -- sfix32_En20 [2]
          x_k_1_k_1                       :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
          P_k_1_k_1                       :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          F                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          Q                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          B                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 1);  -- sfix32_En20 [4x2]
          x_k_k_1                         :   OUT   vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
          P_k_k_1                         :   OUT   matrix_of_std_logic_vector32(0 TO 3, 0 TO 3)  -- sfix32_En20 [4x4]
          );
  END COMPONENT;

  COMPONENT Update
    PORT( x_k_k_1                         :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
          P_k_k_1                         :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          y_k                             :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
          K_k                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          H                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          x_k_k                           :   OUT   vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
          P_k_k                           :   OUT   matrix_of_std_logic_vector32(0 TO 3, 0 TO 3)  -- sfix32_En20 [4x4]
          );
  END COMPONENT;

  COMPONENT New_Innovation
    PORT( x_k_k                           :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
          z_k                             :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
          H                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          y_k_k                           :   OUT   vector_of_std_logic_vector32(0 TO 3)  -- sfix32_En20 [4]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Kalman_Gain_Calculation
    USE ENTITY work.Kalman_Gain_Calculation(rtl);

  FOR ALL : Innovation
    USE ENTITY work.Innovation(rtl);

  FOR ALL : MATLAB_Function_block
    USE ENTITY work.MATLAB_Function_block(rtl);

  FOR ALL : Predict
    USE ENTITY work.Predict(rtl);

  FOR ALL : Update
    USE ENTITY work.Update(rtl);

  FOR ALL : New_Innovation
    USE ENTITY work.New_Innovation(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In2_signed                       : vector_of_signed32(0 TO 1);  -- sfix32_En20 [2]
  SIGNAL Transpose_out1                   : vector_of_signed32(0 TO 1);  -- sfix32_En20 [2]
  SIGNAL Transpose_out1_1                 : vector_of_std_logic_vector32(0 TO 1);  -- ufix32 [2]
  SIGNAL c127_Constant3_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant3_out1                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c332_Constant3_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From2_out1                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From2_out1_1                     : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c101_Constant1_out1              : vector_of_signed32(0 TO 7);  -- sfix32_En20 [8]
  SIGNAL Constant1_out1                   : matrix_of_signed32(0 TO 3, 0 TO 1);  -- sfix32_En20 [4x2]
  SIGNAL c319_Constant1_out1              : vector_of_signed32(0 TO 7);  -- sfix32_En20 [8]
  SIGNAL From3_out1                       : matrix_of_signed32(0 TO 3, 0 TO 1);  -- sfix32_En20 [4x2]
  SIGNAL From3_out1_1                     : matrix_of_std_logic_vector32(0 TO 3, 0 TO 1);  -- ufix32 [4x2]
  SIGNAL In1_signed                       : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Transpose1_out1                  : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Transpose1_out1_1                : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]
  SIGNAL c123_Constant2_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant2_out1                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c330_Constant2_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From4_out1                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From4_out1_1                     : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL From6_out1                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From6_out1_1                     : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c131_Constant5_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant5_out1                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c334_Constant5_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From9_out1                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From9_out1_1                     : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c133_Constant6_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant6_out1                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c335_Constant6_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From10_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From10_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c129_Constant4_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant4_out1                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c333_Constant4_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From5_out1                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From5_out1_1                     : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c135_Constant7_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant7_out1                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c336_Constant7_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From11_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From11_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c137_Constant8_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant8_out1                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c337_Constant8_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From12_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From12_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c103_Constant10_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant10_out1                  : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c320_Constant10_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From13_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From13_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c139_Constant9_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant9_out1                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c338_Constant9_out1              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From16_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From16_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c105_Constant11_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant11_out1                  : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c321_Constant11_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From14_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From14_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c107_Constant12_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant12_out1                  : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c322_Constant12_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From15_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From15_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c117_Constant17_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant17_out1                  : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c327_Constant17_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From17_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From17_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c115_Constant16_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant16_out1                  : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c326_Constant16_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From24_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From24_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c119_Constant18_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant18_out1                  : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c328_Constant18_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From18_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From18_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c121_Constant19_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant19_out1                  : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c329_Constant19_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From19_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From19_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c109_Constant13_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant13_out1                  : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c323_Constant13_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From20_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From20_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c125_Constant20_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant20_out1                  : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c331_Constant20_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From23_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From23_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c111_Constant14_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant14_out1                  : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c324_Constant14_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From21_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From21_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL c113_Constant15_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Constant15_out1                  : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c325_Constant15_out1             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From22_out1                      : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From22_out1_1                    : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL From7_out1                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From7_out1_1                     : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL Predict_P_k_k_1                  : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL Kalman_Gain_Calculation_K_k      : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL Predict_x_k_k_1                  : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]
  SIGNAL Innovation_y_k                   : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]
  SIGNAL Jacobs                           : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL Jacobs_3                         : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous2_out1 : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Jacobs_2                         : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous2_out1_1 : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Jacobs_1                         : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous2_out1_2 : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Update_x_k_k                     : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]
  SIGNAL Jacobs_0                         : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous2_out1_3 : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous2_out1_4 : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c249_Unit_Delay_Enabled_Synchronous2_out1 : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL From1_out1                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From1_out1_1                     : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL Update_P_k_k                     : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL Update_P_k_k_3                   : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1 : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Update_P_k_k_2                   : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_1 : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Update_P_k_k_1                   : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_2 : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Update_P_k_k_0                   : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_3 : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_4 : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_5 : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL Update_x_k_k_signed              : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous_out1 : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Unit_Delay_Enabled_Synchronous_out1_1 : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]
  SIGNAL Transpose1_out1_2                : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]
  SIGNAL From8_out1                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL From8_out1_1                     : matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- ufix32 [4x4]
  SIGNAL New_Innovation_y_k_k             : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]

BEGIN
  u_Kalman_Gain_Calculation : Kalman_Gain_Calculation
    PORT MAP( P_k_k_1 => Predict_P_k_k_1,  -- sfix32_En20 [4x4]
              H => From6_out1_1,  -- sfix32_En20 [4x4]
              C => From9_out1_1,  -- sfix32_En20 [4x4]
              T1 => From10_out1_1,  -- sfix32_En20 [4x4]
              T2 => From5_out1_1,  -- sfix32_En20 [4x4]
              T3 => From11_out1_1,  -- sfix32_En20 [4x4]
              T4 => From12_out1_1,  -- sfix32_En20 [4x4]
              T5 => From13_out1_1,  -- sfix32_En20 [4x4]
              T6 => From16_out1_1,  -- sfix32_En20 [4x4]
              T7 => From14_out1_1,  -- sfix32_En20 [4x4]
              T8 => From15_out1_1,  -- sfix32_En20 [4x4]
              T9 => From17_out1_1,  -- sfix32_En20 [4x4]
              T10 => From24_out1_1,  -- sfix32_En20 [4x4]
              T11 => From18_out1_1,  -- sfix32_En20 [4x4]
              T12 => From19_out1_1,  -- sfix32_En20 [4x4]
              T13 => From20_out1_1,  -- sfix32_En20 [4x4]
              T14 => From23_out1_1,  -- sfix32_En20 [4x4]
              T15 => From21_out1_1,  -- sfix32_En20 [4x4]
              T16 => From22_out1_1,  -- sfix32_En20 [4x4]
              K_k => Kalman_Gain_Calculation_K_k  -- sfix32_En20 [4x4]
              );

  u_Innovation : Innovation
    PORT MAP( x_k_k_1 => Predict_x_k_k_1,  -- sfix32_En20 [4]
              z_k => Transpose1_out1_1,  -- sfix32_En20 [4]
              H => From4_out1_1,  -- sfix32_En20 [4x4]
              y_k => Innovation_y_k  -- sfix32_En20 [4]
              );

  u_MATLAB_Function : MATLAB_Function_block
    PORT MAP( xkk => Update_x_k_k,  -- sfix32_En20 [4]
              Jacobs => Jacobs  -- sfix32_En20 [4x4]
              );

  u_Predict : Predict
    PORT MAP( u_k => Transpose_out1_1,  -- sfix32_En20 [2]
              x_k_1_k_1 => Unit_Delay_Enabled_Synchronous_out1_1,  -- sfix32_En20 [4]
              P_k_1_k_1 => Unit_Delay_Enabled_Synchronous1_out1_5,  -- sfix32_En20 [4x4]
              F => From1_out1_1,  -- sfix32_En20 [4x4]
              Q => From2_out1_1,  -- sfix32_En20 [4x4]
              B => From3_out1_1,  -- sfix32_En20 [4x2]
              x_k_k_1 => Predict_x_k_k_1,  -- sfix32_En20 [4]
              P_k_k_1 => Predict_P_k_k_1  -- sfix32_En20 [4x4]
              );

  u_Update : Update
    PORT MAP( x_k_k_1 => Predict_x_k_k_1,  -- sfix32_En20 [4]
              P_k_k_1 => Predict_P_k_k_1,  -- sfix32_En20 [4x4]
              y_k => Innovation_y_k,  -- sfix32_En20 [4]
              K_k => Kalman_Gain_Calculation_K_k,  -- sfix32_En20 [4x4]
              H => From7_out1_1,  -- sfix32_En20 [4x4]
              x_k_k => Update_x_k_k,  -- sfix32_En20 [4]
              P_k_k => Update_P_k_k  -- sfix32_En20 [4x4]
              );

  u_New_Innovation : New_Innovation
    PORT MAP( x_k_k => Update_x_k_k,  -- sfix32_En20 [4]
              z_k => Transpose1_out1_2,  -- sfix32_En20 [4]
              H => From8_out1_1,  -- sfix32_En20 [4x4]
              y_k_k => New_Innovation_y_k_k  -- sfix32_En20 [4]
              );

  enb <= clk_enable;

  outputgen56: FOR k IN 0 TO 1 GENERATE
    In2_signed(k) <= signed(In2(k));
  END GENERATE;

  Transpose_out1 <= In2_signed;

  outputgen55: FOR k IN 0 TO 1 GENERATE
    Transpose_out1_1(k) <= std_logic_vector(Transpose_out1(k));
  END GENERATE;

  c127_Constant3_out1(0) <= to_signed(104858, 32);
  c127_Constant3_out1(1) <= to_signed(0, 32);
  c127_Constant3_out1(2) <= to_signed(0, 32);
  c127_Constant3_out1(3) <= to_signed(0, 32);
  c127_Constant3_out1(4) <= to_signed(0, 32);
  c127_Constant3_out1(5) <= to_signed(104858, 32);
  c127_Constant3_out1(6) <= to_signed(0, 32);
  c127_Constant3_out1(7) <= to_signed(0, 32);
  c127_Constant3_out1(8) <= to_signed(0, 32);
  c127_Constant3_out1(9) <= to_signed(0, 32);
  c127_Constant3_out1(10) <= to_signed(104858, 32);
  c127_Constant3_out1(11) <= to_signed(0, 32);
  c127_Constant3_out1(12) <= to_signed(0, 32);
  c127_Constant3_out1(13) <= to_signed(0, 32);
  c127_Constant3_out1(14) <= to_signed(0, 32);
  c127_Constant3_out1(15) <= to_signed(104858, 32);

  Constant3_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant3_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant3_out1(d0, d1) <= c127_Constant3_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c332_Constant3_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c332_Constant3_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c332_Constant3_out1(d0 + (d1 * 4)) <= Constant3_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From2_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From2_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From2_out1(d0, d1) <= c332_Constant3_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen53: FOR k IN 0 TO 3 GENERATE
    outputgen54: FOR k1 IN 0 TO 3 GENERATE
      From2_out1_1(k, k1) <= std_logic_vector(From2_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c101_Constant1_out1(0) <= to_signed(210, 32);
  c101_Constant1_out1(1) <= to_signed(0, 32);
  c101_Constant1_out1(2) <= to_signed(20972, 32);
  c101_Constant1_out1(3) <= to_signed(0, 32);
  c101_Constant1_out1(4) <= to_signed(0, 32);
  c101_Constant1_out1(5) <= to_signed(210, 32);
  c101_Constant1_out1(6) <= to_signed(0, 32);
  c101_Constant1_out1(7) <= to_signed(20972, 32);

  Constant1_out1_gen1: FOR d1 IN 0 TO 1 GENERATE
    Constant1_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant1_out1(d0, d1) <= c101_Constant1_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c319_Constant1_out1_gen1: FOR d1 IN 0 TO 1 GENERATE
    c319_Constant1_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c319_Constant1_out1(d0 + (d1 * 4)) <= Constant1_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From3_out1_gen1: FOR d1 IN 0 TO 1 GENERATE
    From3_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From3_out1(d0, d1) <= c319_Constant1_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen51: FOR k IN 0 TO 3 GENERATE
    outputgen52: FOR k1 IN 0 TO 1 GENERATE
      From3_out1_1(k, k1) <= std_logic_vector(From3_out1(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen50: FOR k IN 0 TO 3 GENERATE
    In1_signed(k) <= signed(In1(k));
  END GENERATE;

  Transpose1_out1 <= In1_signed;

  outputgen49: FOR k IN 0 TO 3 GENERATE
    Transpose1_out1_1(k) <= std_logic_vector(Transpose1_out1(k));
  END GENERATE;

  c123_Constant2_out1(0) <= to_signed(1048576, 32);
  c123_Constant2_out1(1) <= to_signed(0, 32);
  c123_Constant2_out1(2) <= to_signed(0, 32);
  c123_Constant2_out1(3) <= to_signed(0, 32);
  c123_Constant2_out1(4) <= to_signed(0, 32);
  c123_Constant2_out1(5) <= to_signed(1048576, 32);
  c123_Constant2_out1(6) <= to_signed(0, 32);
  c123_Constant2_out1(7) <= to_signed(0, 32);
  c123_Constant2_out1(8) <= to_signed(0, 32);
  c123_Constant2_out1(9) <= to_signed(0, 32);
  c123_Constant2_out1(10) <= to_signed(1048576, 32);
  c123_Constant2_out1(11) <= to_signed(0, 32);
  c123_Constant2_out1(12) <= to_signed(0, 32);
  c123_Constant2_out1(13) <= to_signed(0, 32);
  c123_Constant2_out1(14) <= to_signed(0, 32);
  c123_Constant2_out1(15) <= to_signed(1048576, 32);

  Constant2_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant2_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant2_out1(d0, d1) <= c123_Constant2_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c330_Constant2_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c330_Constant2_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c330_Constant2_out1(d0 + (d1 * 4)) <= Constant2_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From4_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From4_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From4_out1(d0, d1) <= c330_Constant2_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen47: FOR k IN 0 TO 3 GENERATE
    outputgen48: FOR k1 IN 0 TO 3 GENERATE
      From4_out1_1(k, k1) <= std_logic_vector(From4_out1(k, k1));
    END GENERATE;
  END GENERATE;

  From6_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From6_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From6_out1(d0, d1) <= c330_Constant2_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen45: FOR k IN 0 TO 3 GENERATE
    outputgen46: FOR k1 IN 0 TO 3 GENERATE
      From6_out1_1(k, k1) <= std_logic_vector(From6_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c131_Constant5_out1(0) <= to_signed(524288, 32);
  c131_Constant5_out1(1) <= to_signed(0, 32);
  c131_Constant5_out1(2) <= to_signed(0, 32);
  c131_Constant5_out1(3) <= to_signed(0, 32);
  c131_Constant5_out1(4) <= to_signed(0, 32);
  c131_Constant5_out1(5) <= to_signed(524288, 32);
  c131_Constant5_out1(6) <= to_signed(0, 32);
  c131_Constant5_out1(7) <= to_signed(0, 32);
  c131_Constant5_out1(8) <= to_signed(0, 32);
  c131_Constant5_out1(9) <= to_signed(0, 32);
  c131_Constant5_out1(10) <= to_signed(953251, 32);
  c131_Constant5_out1(11) <= to_signed(0, 32);
  c131_Constant5_out1(12) <= to_signed(0, 32);
  c131_Constant5_out1(13) <= to_signed(0, 32);
  c131_Constant5_out1(14) <= to_signed(0, 32);
  c131_Constant5_out1(15) <= to_signed(953251, 32);

  Constant5_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant5_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant5_out1(d0, d1) <= c131_Constant5_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c334_Constant5_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c334_Constant5_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c334_Constant5_out1(d0 + (d1 * 4)) <= Constant5_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From9_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From9_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From9_out1(d0, d1) <= c334_Constant5_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen43: FOR k IN 0 TO 3 GENERATE
    outputgen44: FOR k1 IN 0 TO 3 GENERATE
      From9_out1_1(k, k1) <= std_logic_vector(From9_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c133_Constant6_out1(0) <= to_signed(262144, 32);
  c133_Constant6_out1(1) <= to_signed(0, 32);
  c133_Constant6_out1(2) <= to_signed(0, 32);
  c133_Constant6_out1(3) <= to_signed(0, 32);
  c133_Constant6_out1(4) <= to_signed(0, 32);
  c133_Constant6_out1(5) <= to_signed(0, 32);
  c133_Constant6_out1(6) <= to_signed(0, 32);
  c133_Constant6_out1(7) <= to_signed(0, 32);
  c133_Constant6_out1(8) <= to_signed(0, 32);
  c133_Constant6_out1(9) <= to_signed(0, 32);
  c133_Constant6_out1(10) <= to_signed(0, 32);
  c133_Constant6_out1(11) <= to_signed(0, 32);
  c133_Constant6_out1(12) <= to_signed(0, 32);
  c133_Constant6_out1(13) <= to_signed(0, 32);
  c133_Constant6_out1(14) <= to_signed(0, 32);
  c133_Constant6_out1(15) <= to_signed(0, 32);

  Constant6_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant6_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant6_out1(d0, d1) <= c133_Constant6_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c335_Constant6_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c335_Constant6_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c335_Constant6_out1(d0 + (d1 * 4)) <= Constant6_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From10_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From10_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From10_out1(d0, d1) <= c335_Constant6_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen41: FOR k IN 0 TO 3 GENERATE
    outputgen42: FOR k1 IN 0 TO 3 GENERATE
      From10_out1_1(k, k1) <= std_logic_vector(From10_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c129_Constant4_out1(0) <= to_signed(0, 32);
  c129_Constant4_out1(1) <= to_signed(0, 32);
  c129_Constant4_out1(2) <= to_signed(0, 32);
  c129_Constant4_out1(3) <= to_signed(0, 32);
  c129_Constant4_out1(4) <= to_signed(262144, 32);
  c129_Constant4_out1(5) <= to_signed(0, 32);
  c129_Constant4_out1(6) <= to_signed(0, 32);
  c129_Constant4_out1(7) <= to_signed(0, 32);
  c129_Constant4_out1(8) <= to_signed(0, 32);
  c129_Constant4_out1(9) <= to_signed(0, 32);
  c129_Constant4_out1(10) <= to_signed(0, 32);
  c129_Constant4_out1(11) <= to_signed(0, 32);
  c129_Constant4_out1(12) <= to_signed(0, 32);
  c129_Constant4_out1(13) <= to_signed(0, 32);
  c129_Constant4_out1(14) <= to_signed(0, 32);
  c129_Constant4_out1(15) <= to_signed(0, 32);

  Constant4_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant4_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant4_out1(d0, d1) <= c129_Constant4_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c333_Constant4_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c333_Constant4_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c333_Constant4_out1(d0 + (d1 * 4)) <= Constant4_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From5_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From5_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From5_out1(d0, d1) <= c333_Constant4_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen39: FOR k IN 0 TO 3 GENERATE
    outputgen40: FOR k1 IN 0 TO 3 GENERATE
      From5_out1_1(k, k1) <= std_logic_vector(From5_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c135_Constant7_out1(0) <= to_signed(0, 32);
  c135_Constant7_out1(1) <= to_signed(0, 32);
  c135_Constant7_out1(2) <= to_signed(0, 32);
  c135_Constant7_out1(3) <= to_signed(0, 32);
  c135_Constant7_out1(4) <= to_signed(0, 32);
  c135_Constant7_out1(5) <= to_signed(0, 32);
  c135_Constant7_out1(6) <= to_signed(0, 32);
  c135_Constant7_out1(7) <= to_signed(0, 32);
  c135_Constant7_out1(8) <= to_signed(476625, 32);
  c135_Constant7_out1(9) <= to_signed(0, 32);
  c135_Constant7_out1(10) <= to_signed(0, 32);
  c135_Constant7_out1(11) <= to_signed(0, 32);
  c135_Constant7_out1(12) <= to_signed(0, 32);
  c135_Constant7_out1(13) <= to_signed(0, 32);
  c135_Constant7_out1(14) <= to_signed(0, 32);
  c135_Constant7_out1(15) <= to_signed(0, 32);

  Constant7_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant7_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant7_out1(d0, d1) <= c135_Constant7_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c336_Constant7_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c336_Constant7_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c336_Constant7_out1(d0 + (d1 * 4)) <= Constant7_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From11_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From11_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From11_out1(d0, d1) <= c336_Constant7_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen37: FOR k IN 0 TO 3 GENERATE
    outputgen38: FOR k1 IN 0 TO 3 GENERATE
      From11_out1_1(k, k1) <= std_logic_vector(From11_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c137_Constant8_out1(0) <= to_signed(0, 32);
  c137_Constant8_out1(1) <= to_signed(0, 32);
  c137_Constant8_out1(2) <= to_signed(0, 32);
  c137_Constant8_out1(3) <= to_signed(0, 32);
  c137_Constant8_out1(4) <= to_signed(0, 32);
  c137_Constant8_out1(5) <= to_signed(0, 32);
  c137_Constant8_out1(6) <= to_signed(0, 32);
  c137_Constant8_out1(7) <= to_signed(0, 32);
  c137_Constant8_out1(8) <= to_signed(0, 32);
  c137_Constant8_out1(9) <= to_signed(0, 32);
  c137_Constant8_out1(10) <= to_signed(0, 32);
  c137_Constant8_out1(11) <= to_signed(0, 32);
  c137_Constant8_out1(12) <= to_signed(476625, 32);
  c137_Constant8_out1(13) <= to_signed(0, 32);
  c137_Constant8_out1(14) <= to_signed(0, 32);
  c137_Constant8_out1(15) <= to_signed(0, 32);

  Constant8_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant8_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant8_out1(d0, d1) <= c137_Constant8_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c337_Constant8_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c337_Constant8_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c337_Constant8_out1(d0 + (d1 * 4)) <= Constant8_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From12_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From12_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From12_out1(d0, d1) <= c337_Constant8_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen35: FOR k IN 0 TO 3 GENERATE
    outputgen36: FOR k1 IN 0 TO 3 GENERATE
      From12_out1_1(k, k1) <= std_logic_vector(From12_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c103_Constant10_out1(0) <= to_signed(0, 32);
  c103_Constant10_out1(1) <= to_signed(262144, 32);
  c103_Constant10_out1(2) <= to_signed(0, 32);
  c103_Constant10_out1(3) <= to_signed(0, 32);
  c103_Constant10_out1(4) <= to_signed(0, 32);
  c103_Constant10_out1(5) <= to_signed(0, 32);
  c103_Constant10_out1(6) <= to_signed(0, 32);
  c103_Constant10_out1(7) <= to_signed(0, 32);
  c103_Constant10_out1(8) <= to_signed(0, 32);
  c103_Constant10_out1(9) <= to_signed(0, 32);
  c103_Constant10_out1(10) <= to_signed(0, 32);
  c103_Constant10_out1(11) <= to_signed(0, 32);
  c103_Constant10_out1(12) <= to_signed(0, 32);
  c103_Constant10_out1(13) <= to_signed(0, 32);
  c103_Constant10_out1(14) <= to_signed(0, 32);
  c103_Constant10_out1(15) <= to_signed(0, 32);

  Constant10_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant10_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant10_out1(d0, d1) <= c103_Constant10_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c320_Constant10_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c320_Constant10_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c320_Constant10_out1(d0 + (d1 * 4)) <= Constant10_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From13_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From13_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From13_out1(d0, d1) <= c320_Constant10_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen33: FOR k IN 0 TO 3 GENERATE
    outputgen34: FOR k1 IN 0 TO 3 GENERATE
      From13_out1_1(k, k1) <= std_logic_vector(From13_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c139_Constant9_out1(0) <= to_signed(0, 32);
  c139_Constant9_out1(1) <= to_signed(0, 32);
  c139_Constant9_out1(2) <= to_signed(0, 32);
  c139_Constant9_out1(3) <= to_signed(0, 32);
  c139_Constant9_out1(4) <= to_signed(0, 32);
  c139_Constant9_out1(5) <= to_signed(262144, 32);
  c139_Constant9_out1(6) <= to_signed(0, 32);
  c139_Constant9_out1(7) <= to_signed(0, 32);
  c139_Constant9_out1(8) <= to_signed(0, 32);
  c139_Constant9_out1(9) <= to_signed(0, 32);
  c139_Constant9_out1(10) <= to_signed(0, 32);
  c139_Constant9_out1(11) <= to_signed(0, 32);
  c139_Constant9_out1(12) <= to_signed(0, 32);
  c139_Constant9_out1(13) <= to_signed(0, 32);
  c139_Constant9_out1(14) <= to_signed(0, 32);
  c139_Constant9_out1(15) <= to_signed(0, 32);

  Constant9_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant9_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant9_out1(d0, d1) <= c139_Constant9_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c338_Constant9_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c338_Constant9_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c338_Constant9_out1(d0 + (d1 * 4)) <= Constant9_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From16_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From16_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From16_out1(d0, d1) <= c338_Constant9_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen31: FOR k IN 0 TO 3 GENERATE
    outputgen32: FOR k1 IN 0 TO 3 GENERATE
      From16_out1_1(k, k1) <= std_logic_vector(From16_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c105_Constant11_out1(0) <= to_signed(0, 32);
  c105_Constant11_out1(1) <= to_signed(0, 32);
  c105_Constant11_out1(2) <= to_signed(0, 32);
  c105_Constant11_out1(3) <= to_signed(0, 32);
  c105_Constant11_out1(4) <= to_signed(0, 32);
  c105_Constant11_out1(5) <= to_signed(0, 32);
  c105_Constant11_out1(6) <= to_signed(0, 32);
  c105_Constant11_out1(7) <= to_signed(0, 32);
  c105_Constant11_out1(8) <= to_signed(0, 32);
  c105_Constant11_out1(9) <= to_signed(476625, 32);
  c105_Constant11_out1(10) <= to_signed(0, 32);
  c105_Constant11_out1(11) <= to_signed(0, 32);
  c105_Constant11_out1(12) <= to_signed(0, 32);
  c105_Constant11_out1(13) <= to_signed(0, 32);
  c105_Constant11_out1(14) <= to_signed(0, 32);
  c105_Constant11_out1(15) <= to_signed(0, 32);

  Constant11_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant11_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant11_out1(d0, d1) <= c105_Constant11_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c321_Constant11_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c321_Constant11_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c321_Constant11_out1(d0 + (d1 * 4)) <= Constant11_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From14_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From14_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From14_out1(d0, d1) <= c321_Constant11_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen29: FOR k IN 0 TO 3 GENERATE
    outputgen30: FOR k1 IN 0 TO 3 GENERATE
      From14_out1_1(k, k1) <= std_logic_vector(From14_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c107_Constant12_out1(0) <= to_signed(0, 32);
  c107_Constant12_out1(1) <= to_signed(0, 32);
  c107_Constant12_out1(2) <= to_signed(0, 32);
  c107_Constant12_out1(3) <= to_signed(0, 32);
  c107_Constant12_out1(4) <= to_signed(0, 32);
  c107_Constant12_out1(5) <= to_signed(0, 32);
  c107_Constant12_out1(6) <= to_signed(0, 32);
  c107_Constant12_out1(7) <= to_signed(0, 32);
  c107_Constant12_out1(8) <= to_signed(0, 32);
  c107_Constant12_out1(9) <= to_signed(0, 32);
  c107_Constant12_out1(10) <= to_signed(0, 32);
  c107_Constant12_out1(11) <= to_signed(0, 32);
  c107_Constant12_out1(12) <= to_signed(0, 32);
  c107_Constant12_out1(13) <= to_signed(476625, 32);
  c107_Constant12_out1(14) <= to_signed(0, 32);
  c107_Constant12_out1(15) <= to_signed(0, 32);

  Constant12_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant12_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant12_out1(d0, d1) <= c107_Constant12_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c322_Constant12_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c322_Constant12_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c322_Constant12_out1(d0 + (d1 * 4)) <= Constant12_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From15_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From15_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From15_out1(d0, d1) <= c322_Constant12_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen27: FOR k IN 0 TO 3 GENERATE
    outputgen28: FOR k1 IN 0 TO 3 GENERATE
      From15_out1_1(k, k1) <= std_logic_vector(From15_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c117_Constant17_out1(0) <= to_signed(0, 32);
  c117_Constant17_out1(1) <= to_signed(0, 32);
  c117_Constant17_out1(2) <= to_signed(476625, 32);
  c117_Constant17_out1(3) <= to_signed(0, 32);
  c117_Constant17_out1(4) <= to_signed(0, 32);
  c117_Constant17_out1(5) <= to_signed(0, 32);
  c117_Constant17_out1(6) <= to_signed(0, 32);
  c117_Constant17_out1(7) <= to_signed(0, 32);
  c117_Constant17_out1(8) <= to_signed(0, 32);
  c117_Constant17_out1(9) <= to_signed(0, 32);
  c117_Constant17_out1(10) <= to_signed(0, 32);
  c117_Constant17_out1(11) <= to_signed(0, 32);
  c117_Constant17_out1(12) <= to_signed(0, 32);
  c117_Constant17_out1(13) <= to_signed(0, 32);
  c117_Constant17_out1(14) <= to_signed(0, 32);
  c117_Constant17_out1(15) <= to_signed(0, 32);

  Constant17_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant17_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant17_out1(d0, d1) <= c117_Constant17_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c327_Constant17_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c327_Constant17_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c327_Constant17_out1(d0 + (d1 * 4)) <= Constant17_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From17_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From17_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From17_out1(d0, d1) <= c327_Constant17_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen25: FOR k IN 0 TO 3 GENERATE
    outputgen26: FOR k1 IN 0 TO 3 GENERATE
      From17_out1_1(k, k1) <= std_logic_vector(From17_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c115_Constant16_out1(0) <= to_signed(0, 32);
  c115_Constant16_out1(1) <= to_signed(0, 32);
  c115_Constant16_out1(2) <= to_signed(0, 32);
  c115_Constant16_out1(3) <= to_signed(0, 32);
  c115_Constant16_out1(4) <= to_signed(0, 32);
  c115_Constant16_out1(5) <= to_signed(0, 32);
  c115_Constant16_out1(6) <= to_signed(476625, 32);
  c115_Constant16_out1(7) <= to_signed(0, 32);
  c115_Constant16_out1(8) <= to_signed(0, 32);
  c115_Constant16_out1(9) <= to_signed(0, 32);
  c115_Constant16_out1(10) <= to_signed(0, 32);
  c115_Constant16_out1(11) <= to_signed(0, 32);
  c115_Constant16_out1(12) <= to_signed(0, 32);
  c115_Constant16_out1(13) <= to_signed(0, 32);
  c115_Constant16_out1(14) <= to_signed(0, 32);
  c115_Constant16_out1(15) <= to_signed(0, 32);

  Constant16_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant16_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant16_out1(d0, d1) <= c115_Constant16_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c326_Constant16_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c326_Constant16_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c326_Constant16_out1(d0 + (d1 * 4)) <= Constant16_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From24_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From24_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From24_out1(d0, d1) <= c326_Constant16_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen23: FOR k IN 0 TO 3 GENERATE
    outputgen24: FOR k1 IN 0 TO 3 GENERATE
      From24_out1_1(k, k1) <= std_logic_vector(From24_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c119_Constant18_out1(0) <= to_signed(0, 32);
  c119_Constant18_out1(1) <= to_signed(0, 32);
  c119_Constant18_out1(2) <= to_signed(0, 32);
  c119_Constant18_out1(3) <= to_signed(0, 32);
  c119_Constant18_out1(4) <= to_signed(0, 32);
  c119_Constant18_out1(5) <= to_signed(0, 32);
  c119_Constant18_out1(6) <= to_signed(0, 32);
  c119_Constant18_out1(7) <= to_signed(0, 32);
  c119_Constant18_out1(8) <= to_signed(0, 32);
  c119_Constant18_out1(9) <= to_signed(0, 32);
  c119_Constant18_out1(10) <= to_signed(866592, 32);
  c119_Constant18_out1(11) <= to_signed(0, 32);
  c119_Constant18_out1(12) <= to_signed(0, 32);
  c119_Constant18_out1(13) <= to_signed(0, 32);
  c119_Constant18_out1(14) <= to_signed(0, 32);
  c119_Constant18_out1(15) <= to_signed(0, 32);

  Constant18_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant18_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant18_out1(d0, d1) <= c119_Constant18_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c328_Constant18_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c328_Constant18_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c328_Constant18_out1(d0 + (d1 * 4)) <= Constant18_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From18_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From18_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From18_out1(d0, d1) <= c328_Constant18_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen21: FOR k IN 0 TO 3 GENERATE
    outputgen22: FOR k1 IN 0 TO 3 GENERATE
      From18_out1_1(k, k1) <= std_logic_vector(From18_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c121_Constant19_out1(0) <= to_signed(0, 32);
  c121_Constant19_out1(1) <= to_signed(0, 32);
  c121_Constant19_out1(2) <= to_signed(0, 32);
  c121_Constant19_out1(3) <= to_signed(0, 32);
  c121_Constant19_out1(4) <= to_signed(0, 32);
  c121_Constant19_out1(5) <= to_signed(0, 32);
  c121_Constant19_out1(6) <= to_signed(0, 32);
  c121_Constant19_out1(7) <= to_signed(0, 32);
  c121_Constant19_out1(8) <= to_signed(0, 32);
  c121_Constant19_out1(9) <= to_signed(0, 32);
  c121_Constant19_out1(10) <= to_signed(0, 32);
  c121_Constant19_out1(11) <= to_signed(0, 32);
  c121_Constant19_out1(12) <= to_signed(0, 32);
  c121_Constant19_out1(13) <= to_signed(0, 32);
  c121_Constant19_out1(14) <= to_signed(866592, 32);
  c121_Constant19_out1(15) <= to_signed(0, 32);

  Constant19_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant19_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant19_out1(d0, d1) <= c121_Constant19_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c329_Constant19_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c329_Constant19_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c329_Constant19_out1(d0 + (d1 * 4)) <= Constant19_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From19_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From19_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From19_out1(d0, d1) <= c329_Constant19_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen19: FOR k IN 0 TO 3 GENERATE
    outputgen20: FOR k1 IN 0 TO 3 GENERATE
      From19_out1_1(k, k1) <= std_logic_vector(From19_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c109_Constant13_out1(0) <= to_signed(0, 32);
  c109_Constant13_out1(1) <= to_signed(0, 32);
  c109_Constant13_out1(2) <= to_signed(0, 32);
  c109_Constant13_out1(3) <= to_signed(476625, 32);
  c109_Constant13_out1(4) <= to_signed(0, 32);
  c109_Constant13_out1(5) <= to_signed(0, 32);
  c109_Constant13_out1(6) <= to_signed(0, 32);
  c109_Constant13_out1(7) <= to_signed(0, 32);
  c109_Constant13_out1(8) <= to_signed(0, 32);
  c109_Constant13_out1(9) <= to_signed(0, 32);
  c109_Constant13_out1(10) <= to_signed(0, 32);
  c109_Constant13_out1(11) <= to_signed(0, 32);
  c109_Constant13_out1(12) <= to_signed(0, 32);
  c109_Constant13_out1(13) <= to_signed(0, 32);
  c109_Constant13_out1(14) <= to_signed(0, 32);
  c109_Constant13_out1(15) <= to_signed(0, 32);

  Constant13_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant13_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant13_out1(d0, d1) <= c109_Constant13_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c323_Constant13_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c323_Constant13_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c323_Constant13_out1(d0 + (d1 * 4)) <= Constant13_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From20_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From20_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From20_out1(d0, d1) <= c323_Constant13_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen17: FOR k IN 0 TO 3 GENERATE
    outputgen18: FOR k1 IN 0 TO 3 GENERATE
      From20_out1_1(k, k1) <= std_logic_vector(From20_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c125_Constant20_out1(0) <= to_signed(0, 32);
  c125_Constant20_out1(1) <= to_signed(0, 32);
  c125_Constant20_out1(2) <= to_signed(0, 32);
  c125_Constant20_out1(3) <= to_signed(0, 32);
  c125_Constant20_out1(4) <= to_signed(0, 32);
  c125_Constant20_out1(5) <= to_signed(0, 32);
  c125_Constant20_out1(6) <= to_signed(0, 32);
  c125_Constant20_out1(7) <= to_signed(476625, 32);
  c125_Constant20_out1(8) <= to_signed(0, 32);
  c125_Constant20_out1(9) <= to_signed(0, 32);
  c125_Constant20_out1(10) <= to_signed(0, 32);
  c125_Constant20_out1(11) <= to_signed(0, 32);
  c125_Constant20_out1(12) <= to_signed(0, 32);
  c125_Constant20_out1(13) <= to_signed(0, 32);
  c125_Constant20_out1(14) <= to_signed(0, 32);
  c125_Constant20_out1(15) <= to_signed(0, 32);

  Constant20_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant20_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant20_out1(d0, d1) <= c125_Constant20_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c331_Constant20_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c331_Constant20_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c331_Constant20_out1(d0 + (d1 * 4)) <= Constant20_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From23_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From23_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From23_out1(d0, d1) <= c331_Constant20_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen15: FOR k IN 0 TO 3 GENERATE
    outputgen16: FOR k1 IN 0 TO 3 GENERATE
      From23_out1_1(k, k1) <= std_logic_vector(From23_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c111_Constant14_out1(0) <= to_signed(0, 32);
  c111_Constant14_out1(1) <= to_signed(0, 32);
  c111_Constant14_out1(2) <= to_signed(0, 32);
  c111_Constant14_out1(3) <= to_signed(0, 32);
  c111_Constant14_out1(4) <= to_signed(0, 32);
  c111_Constant14_out1(5) <= to_signed(0, 32);
  c111_Constant14_out1(6) <= to_signed(0, 32);
  c111_Constant14_out1(7) <= to_signed(0, 32);
  c111_Constant14_out1(8) <= to_signed(0, 32);
  c111_Constant14_out1(9) <= to_signed(0, 32);
  c111_Constant14_out1(10) <= to_signed(0, 32);
  c111_Constant14_out1(11) <= to_signed(866592, 32);
  c111_Constant14_out1(12) <= to_signed(0, 32);
  c111_Constant14_out1(13) <= to_signed(0, 32);
  c111_Constant14_out1(14) <= to_signed(0, 32);
  c111_Constant14_out1(15) <= to_signed(0, 32);

  Constant14_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant14_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant14_out1(d0, d1) <= c111_Constant14_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c324_Constant14_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c324_Constant14_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c324_Constant14_out1(d0 + (d1 * 4)) <= Constant14_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From21_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From21_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From21_out1(d0, d1) <= c324_Constant14_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen13: FOR k IN 0 TO 3 GENERATE
    outputgen14: FOR k1 IN 0 TO 3 GENERATE
      From21_out1_1(k, k1) <= std_logic_vector(From21_out1(k, k1));
    END GENERATE;
  END GENERATE;

  c113_Constant15_out1(0) <= to_signed(0, 32);
  c113_Constant15_out1(1) <= to_signed(0, 32);
  c113_Constant15_out1(2) <= to_signed(0, 32);
  c113_Constant15_out1(3) <= to_signed(0, 32);
  c113_Constant15_out1(4) <= to_signed(0, 32);
  c113_Constant15_out1(5) <= to_signed(0, 32);
  c113_Constant15_out1(6) <= to_signed(0, 32);
  c113_Constant15_out1(7) <= to_signed(0, 32);
  c113_Constant15_out1(8) <= to_signed(0, 32);
  c113_Constant15_out1(9) <= to_signed(0, 32);
  c113_Constant15_out1(10) <= to_signed(0, 32);
  c113_Constant15_out1(11) <= to_signed(0, 32);
  c113_Constant15_out1(12) <= to_signed(0, 32);
  c113_Constant15_out1(13) <= to_signed(0, 32);
  c113_Constant15_out1(14) <= to_signed(0, 32);
  c113_Constant15_out1(15) <= to_signed(866592, 32);

  Constant15_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Constant15_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Constant15_out1(d0, d1) <= c113_Constant15_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c325_Constant15_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c325_Constant15_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c325_Constant15_out1(d0 + (d1 * 4)) <= Constant15_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  From22_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From22_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From22_out1(d0, d1) <= c325_Constant15_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen11: FOR k IN 0 TO 3 GENERATE
    outputgen12: FOR k1 IN 0 TO 3 GENERATE
      From22_out1_1(k, k1) <= std_logic_vector(From22_out1(k, k1));
    END GENERATE;
  END GENERATE;

  From7_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From7_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From7_out1(d0, d1) <= c330_Constant2_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen9: FOR k IN 0 TO 3 GENERATE
    outputgen10: FOR k1 IN 0 TO 3 GENERATE
      From7_out1_1(k, k1) <= std_logic_vector(From7_out1(k, k1));
    END GENERATE;
  END GENERATE;

  Jacobs_3(0) <= signed(Jacobs(0, 3));
  Jacobs_3(1) <= signed(Jacobs(1, 3));
  Jacobs_3(2) <= signed(Jacobs(2, 3));
  Jacobs_3(3) <= signed(Jacobs(3, 3));

  Unit_Delay_Enabled_Synchronous2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous2_out1 <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND E = '1' THEN
        Unit_Delay_Enabled_Synchronous2_out1 <= Jacobs_3;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous2_process;


  Jacobs_2(0) <= signed(Jacobs(0, 2));
  Jacobs_2(1) <= signed(Jacobs(1, 2));
  Jacobs_2(2) <= signed(Jacobs(2, 2));
  Jacobs_2(3) <= signed(Jacobs(3, 2));

  Unit_Delay_Enabled_Synchronous2_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous2_out1_1 <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND E = '1' THEN
        Unit_Delay_Enabled_Synchronous2_out1_1 <= Jacobs_2;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous2_1_process;


  Jacobs_1(0) <= signed(Jacobs(0, 1));
  Jacobs_1(1) <= signed(Jacobs(1, 1));
  Jacobs_1(2) <= signed(Jacobs(2, 1));
  Jacobs_1(3) <= signed(Jacobs(3, 1));

  Unit_Delay_Enabled_Synchronous2_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous2_out1_2 <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND E = '1' THEN
        Unit_Delay_Enabled_Synchronous2_out1_2 <= Jacobs_1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous2_2_process;


  Jacobs_0(0) <= signed(Jacobs(0, 0));
  Jacobs_0(1) <= signed(Jacobs(1, 0));
  Jacobs_0(2) <= signed(Jacobs(2, 0));
  Jacobs_0(3) <= signed(Jacobs(3, 0));

  Unit_Delay_Enabled_Synchronous2_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous2_out1_3 <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND E = '1' THEN
        Unit_Delay_Enabled_Synchronous2_out1_3 <= Jacobs_0;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous2_3_process;


  Unit_Delay_Enabled_Synchronous2_out1_4_gen: FOR idx IN 0 TO 3 GENERATE
    Unit_Delay_Enabled_Synchronous2_out1_4(idx, 0) <= Unit_Delay_Enabled_Synchronous2_out1_3(idx);
  END GENERATE;
  Unit_Delay_Enabled_Synchronous2_out1_4_gen1: FOR idx IN 0 TO 3 GENERATE
    Unit_Delay_Enabled_Synchronous2_out1_4(idx, 1) <= Unit_Delay_Enabled_Synchronous2_out1_2(idx);
  END GENERATE;
  Unit_Delay_Enabled_Synchronous2_out1_4_gen2: FOR idx IN 0 TO 3 GENERATE
    Unit_Delay_Enabled_Synchronous2_out1_4(idx, 2) <= Unit_Delay_Enabled_Synchronous2_out1_1(idx);
  END GENERATE;
  Unit_Delay_Enabled_Synchronous2_out1_4_gen3: FOR idx IN 0 TO 3 GENERATE
    Unit_Delay_Enabled_Synchronous2_out1_4(idx, 3) <= Unit_Delay_Enabled_Synchronous2_out1(idx);
  END GENERATE;

  c249_Unit_Delay_Enabled_Synchronous2_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c249_Unit_Delay_Enabled_Synchronous2_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c249_Unit_Delay_Enabled_Synchronous2_out1(d0 + (d1 * 4)) <= Unit_Delay_Enabled_Synchronous2_out1_4(d0, d1);
    END GENERATE;
  END GENERATE;

  From1_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From1_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From1_out1(d0, d1) <= c249_Unit_Delay_Enabled_Synchronous2_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen7: FOR k IN 0 TO 3 GENERATE
    outputgen8: FOR k1 IN 0 TO 3 GENERATE
      From1_out1_1(k, k1) <= std_logic_vector(From1_out1(k, k1));
    END GENERATE;
  END GENERATE;

  Update_P_k_k_3(0) <= signed(Update_P_k_k(0, 3));
  Update_P_k_k_3(1) <= signed(Update_P_k_k(1, 3));
  Update_P_k_k_3(2) <= signed(Update_P_k_k(2, 3));
  Update_P_k_k_3(3) <= signed(Update_P_k_k(3, 3));

  Unit_Delay_Enabled_Synchronous1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous1_out1 <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND E = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1 <= Update_P_k_k_3;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous1_process;


  Update_P_k_k_2(0) <= signed(Update_P_k_k(0, 2));
  Update_P_k_k_2(1) <= signed(Update_P_k_k(1, 2));
  Update_P_k_k_2(2) <= signed(Update_P_k_k(2, 2));
  Update_P_k_k_2(3) <= signed(Update_P_k_k(3, 2));

  Unit_Delay_Enabled_Synchronous1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous1_out1_1 <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND E = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_1 <= Update_P_k_k_2;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous1_1_process;


  Update_P_k_k_1(0) <= signed(Update_P_k_k(0, 1));
  Update_P_k_k_1(1) <= signed(Update_P_k_k(1, 1));
  Update_P_k_k_1(2) <= signed(Update_P_k_k(2, 1));
  Update_P_k_k_1(3) <= signed(Update_P_k_k(3, 1));

  Unit_Delay_Enabled_Synchronous1_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous1_out1_2 <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND E = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_2 <= Update_P_k_k_1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous1_2_process;


  Update_P_k_k_0(0) <= signed(Update_P_k_k(0, 0));
  Update_P_k_k_0(1) <= signed(Update_P_k_k(1, 0));
  Update_P_k_k_0(2) <= signed(Update_P_k_k(2, 0));
  Update_P_k_k_0(3) <= signed(Update_P_k_k(3, 0));

  Unit_Delay_Enabled_Synchronous1_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous1_out1_3 <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND E = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_3 <= Update_P_k_k_0;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous1_3_process;


  Unit_Delay_Enabled_Synchronous1_out1_4_gen: FOR idx IN 0 TO 3 GENERATE
    Unit_Delay_Enabled_Synchronous1_out1_4(idx, 0) <= Unit_Delay_Enabled_Synchronous1_out1_3(idx);
  END GENERATE;
  Unit_Delay_Enabled_Synchronous1_out1_4_gen1: FOR idx IN 0 TO 3 GENERATE
    Unit_Delay_Enabled_Synchronous1_out1_4(idx, 1) <= Unit_Delay_Enabled_Synchronous1_out1_2(idx);
  END GENERATE;
  Unit_Delay_Enabled_Synchronous1_out1_4_gen2: FOR idx IN 0 TO 3 GENERATE
    Unit_Delay_Enabled_Synchronous1_out1_4(idx, 2) <= Unit_Delay_Enabled_Synchronous1_out1_1(idx);
  END GENERATE;
  Unit_Delay_Enabled_Synchronous1_out1_4_gen3: FOR idx IN 0 TO 3 GENERATE
    Unit_Delay_Enabled_Synchronous1_out1_4(idx, 3) <= Unit_Delay_Enabled_Synchronous1_out1(idx);
  END GENERATE;

  outputgen5: FOR k IN 0 TO 3 GENERATE
    outputgen6: FOR k1 IN 0 TO 3 GENERATE
      Unit_Delay_Enabled_Synchronous1_out1_5(k, k1) <= std_logic_vector(Unit_Delay_Enabled_Synchronous1_out1_4(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen4: FOR k IN 0 TO 3 GENERATE
    Update_x_k_k_signed(k) <= signed(Update_x_k_k(k));
  END GENERATE;

  Unit_Delay_Enabled_Synchronous_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous_out1 <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND E = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1 <= Update_x_k_k_signed;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous_process;


  outputgen3: FOR k IN 0 TO 3 GENERATE
    Unit_Delay_Enabled_Synchronous_out1_1(k) <= std_logic_vector(Unit_Delay_Enabled_Synchronous_out1(k));
  END GENERATE;

  outputgen2: FOR k IN 0 TO 3 GENERATE
    Transpose1_out1_2(k) <= std_logic_vector(Transpose1_out1(k));
  END GENERATE;

  From8_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    From8_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      From8_out1(d0, d1) <= c330_Constant2_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen: FOR k IN 0 TO 3 GENERATE
    outputgen1: FOR k1 IN 0 TO 3 GENERATE
      From8_out1_1(k, k1) <= std_logic_vector(From8_out1(k, k1));
    END GENERATE;
  END GENERATE;

  ce_out <= clk_enable;

  y_k_k <= New_Innovation_y_k_k;

  u <= Update_x_k_k;

END rtl;

