-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\EkalmanF_ac_sim\Inverse_aprox.vhd
-- Created: 2026-01-12 14:16:47
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Inverse_aprox
-- Source Path: EkalmanF_ac_sim/EKF/Kalman Gain Calculation/Inverse_aprox
-- Hierarchy Level: 2
-- Model version: 1.76
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.EKF_pkg.ALL;

ENTITY Inverse_aprox IS
  PORT( P_k                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        C                                 :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T1                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T2                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T3                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T4                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T5                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T6                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T7                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T8                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T9                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T10                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T11                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T12                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T13                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T14                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T15                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T16                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        S_k_inv                           :   OUT   matrix_of_std_logic_vector33(0 TO 3, 0 TO 3)  -- sfix33_En20 [4x4]
        );
END Inverse_aprox;


ARCHITECTURE rtl OF Inverse_aprox IS

  -- Constants
  CONSTANT nc                             : matrix_of_signed67(0 TO 3, 0 TO 3) := 
    (( signed'("0000000000000000000000000010000000000000000000000000000000000000000"), to_signed(0, 67),
     to_signed(0, 67), to_signed(0, 67) ), ( to_signed(0, 67),
     signed'("0000000000000000000000000010000000000000000000000000000000000000000"), to_signed(0, 67),
     to_signed(0, 67) ), ( to_signed(0, 67), to_signed(0, 67),
     signed'("0000000000000000000000000010000000000000000000000000000000000000000"), to_signed(0, 67) ),
     ( to_signed(0, 67), to_signed(0, 67), to_signed(0, 67),
     signed'("0000000000000000000000000010000000000000000000000000000000000000000") ));  -- sfix67 [4x4]

  -- Signals
  SIGNAL P_k_signed                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL C_signed                         : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T1_signed                        : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T2_signed                        : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T3_signed                        : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T4_signed                        : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T5_signed                        : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T6_signed                        : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T7_signed                        : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T8_signed                        : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T9_signed                        : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T10_signed                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T11_signed                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T12_signed                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T13_signed                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T14_signed                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T15_signed                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL T16_signed                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL S_k_inv_tmp                      : matrix_of_signed33(0 TO 3, 0 TO 3);  -- sfix33_En20 [4x4]

BEGIN
  outputgen36: FOR k IN 0 TO 3 GENERATE
    outputgen37: FOR k1 IN 0 TO 3 GENERATE
      P_k_signed(k, k1) <= signed(P_k(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen34: FOR k IN 0 TO 3 GENERATE
    outputgen35: FOR k1 IN 0 TO 3 GENERATE
      C_signed(k, k1) <= signed(C(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen32: FOR k IN 0 TO 3 GENERATE
    outputgen33: FOR k1 IN 0 TO 3 GENERATE
      T1_signed(k, k1) <= signed(T1(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen30: FOR k IN 0 TO 3 GENERATE
    outputgen31: FOR k1 IN 0 TO 3 GENERATE
      T2_signed(k, k1) <= signed(T2(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen28: FOR k IN 0 TO 3 GENERATE
    outputgen29: FOR k1 IN 0 TO 3 GENERATE
      T3_signed(k, k1) <= signed(T3(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen26: FOR k IN 0 TO 3 GENERATE
    outputgen27: FOR k1 IN 0 TO 3 GENERATE
      T4_signed(k, k1) <= signed(T4(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen24: FOR k IN 0 TO 3 GENERATE
    outputgen25: FOR k1 IN 0 TO 3 GENERATE
      T5_signed(k, k1) <= signed(T5(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen22: FOR k IN 0 TO 3 GENERATE
    outputgen23: FOR k1 IN 0 TO 3 GENERATE
      T6_signed(k, k1) <= signed(T6(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen20: FOR k IN 0 TO 3 GENERATE
    outputgen21: FOR k1 IN 0 TO 3 GENERATE
      T7_signed(k, k1) <= signed(T7(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen18: FOR k IN 0 TO 3 GENERATE
    outputgen19: FOR k1 IN 0 TO 3 GENERATE
      T8_signed(k, k1) <= signed(T8(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen16: FOR k IN 0 TO 3 GENERATE
    outputgen17: FOR k1 IN 0 TO 3 GENERATE
      T9_signed(k, k1) <= signed(T9(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen14: FOR k IN 0 TO 3 GENERATE
    outputgen15: FOR k1 IN 0 TO 3 GENERATE
      T10_signed(k, k1) <= signed(T10(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen12: FOR k IN 0 TO 3 GENERATE
    outputgen13: FOR k1 IN 0 TO 3 GENERATE
      T11_signed(k, k1) <= signed(T11(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen10: FOR k IN 0 TO 3 GENERATE
    outputgen11: FOR k1 IN 0 TO 3 GENERATE
      T12_signed(k, k1) <= signed(T12(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen8: FOR k IN 0 TO 3 GENERATE
    outputgen9: FOR k1 IN 0 TO 3 GENERATE
      T13_signed(k, k1) <= signed(T13(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen6: FOR k IN 0 TO 3 GENERATE
    outputgen7: FOR k1 IN 0 TO 3 GENERATE
      T14_signed(k, k1) <= signed(T14(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen4: FOR k IN 0 TO 3 GENERATE
    outputgen5: FOR k1 IN 0 TO 3 GENERATE
      T15_signed(k, k1) <= signed(T15(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen2: FOR k IN 0 TO 3 GENERATE
    outputgen3: FOR k1 IN 0 TO 3 GENERATE
      T16_signed(k, k1) <= signed(T16(k, k1));
    END GENERATE;
  END GENERATE;

  Inverse_aprox_1_output : PROCESS (C_signed, P_k_signed, T10_signed, T11_signed, T12_signed, T13_signed,
       T14_signed, T15_signed, T16_signed, T1_signed, T2_signed, T3_signed,
       T4_signed, T5_signed, T6_signed, T7_signed, T8_signed, T9_signed)
    VARIABLE Z : matrix_of_signed67(0 TO 3, 0 TO 3);
    VARIABLE sub_cast : signed(66 DOWNTO 0);
    VARIABLE sub_cast_0 : signed(67 DOWNTO 0);
    VARIABLE sub_cast_1 : signed(67 DOWNTO 0);
    VARIABLE sub_temp : signed(67 DOWNTO 0);
    VARIABLE sub_cast_2 : signed(32 DOWNTO 0);
    VARIABLE mul_temp : signed(98 DOWNTO 0);
    VARIABLE add_cast : signed(100 DOWNTO 0);
    VARIABLE mul_temp_0 : signed(98 DOWNTO 0);
    VARIABLE add_cast_0 : signed(100 DOWNTO 0);
    VARIABLE add_temp : signed(100 DOWNTO 0);
    VARIABLE add_cast_1 : signed(101 DOWNTO 0);
    VARIABLE mul_temp_1 : signed(98 DOWNTO 0);
    VARIABLE add_cast_2 : signed(101 DOWNTO 0);
    VARIABLE add_temp_0 : signed(101 DOWNTO 0);
    VARIABLE add_cast_3 : signed(102 DOWNTO 0);
    VARIABLE mul_temp_2 : signed(98 DOWNTO 0);
    VARIABLE add_cast_4 : signed(102 DOWNTO 0);
    VARIABLE add_temp_1 : signed(102 DOWNTO 0);
    VARIABLE add_cast_5 : signed(103 DOWNTO 0);
    VARIABLE mul_temp_3 : signed(98 DOWNTO 0);
    VARIABLE add_cast_6 : signed(103 DOWNTO 0);
    VARIABLE add_temp_2 : signed(103 DOWNTO 0);
    VARIABLE add_cast_7 : signed(104 DOWNTO 0);
    VARIABLE mul_temp_4 : signed(98 DOWNTO 0);
    VARIABLE add_cast_8 : signed(104 DOWNTO 0);
    VARIABLE add_temp_3 : signed(104 DOWNTO 0);
    VARIABLE add_cast_9 : signed(105 DOWNTO 0);
    VARIABLE mul_temp_5 : signed(98 DOWNTO 0);
    VARIABLE add_cast_10 : signed(105 DOWNTO 0);
    VARIABLE add_temp_4 : signed(105 DOWNTO 0);
    VARIABLE add_cast_11 : signed(106 DOWNTO 0);
    VARIABLE mul_temp_6 : signed(98 DOWNTO 0);
    VARIABLE add_cast_12 : signed(106 DOWNTO 0);
    VARIABLE add_temp_5 : signed(106 DOWNTO 0);
    VARIABLE add_cast_13 : signed(107 DOWNTO 0);
    VARIABLE mul_temp_7 : signed(98 DOWNTO 0);
    VARIABLE add_cast_14 : signed(107 DOWNTO 0);
    VARIABLE add_temp_6 : signed(107 DOWNTO 0);
    VARIABLE add_cast_15 : signed(108 DOWNTO 0);
    VARIABLE mul_temp_8 : signed(98 DOWNTO 0);
    VARIABLE add_cast_16 : signed(108 DOWNTO 0);
    VARIABLE add_temp_7 : signed(108 DOWNTO 0);
    VARIABLE add_cast_17 : signed(109 DOWNTO 0);
    VARIABLE mul_temp_9 : signed(98 DOWNTO 0);
    VARIABLE add_cast_18 : signed(109 DOWNTO 0);
    VARIABLE add_temp_8 : signed(109 DOWNTO 0);
    VARIABLE add_cast_19 : signed(110 DOWNTO 0);
    VARIABLE mul_temp_10 : signed(98 DOWNTO 0);
    VARIABLE add_cast_20 : signed(110 DOWNTO 0);
    VARIABLE add_temp_9 : signed(110 DOWNTO 0);
    VARIABLE add_cast_21 : signed(111 DOWNTO 0);
    VARIABLE mul_temp_11 : signed(98 DOWNTO 0);
    VARIABLE add_cast_22 : signed(111 DOWNTO 0);
    VARIABLE add_temp_10 : signed(111 DOWNTO 0);
    VARIABLE add_cast_23 : signed(112 DOWNTO 0);
    VARIABLE mul_temp_12 : signed(98 DOWNTO 0);
    VARIABLE add_cast_24 : signed(112 DOWNTO 0);
    VARIABLE add_temp_11 : signed(112 DOWNTO 0);
    VARIABLE add_cast_25 : signed(113 DOWNTO 0);
    VARIABLE mul_temp_13 : signed(98 DOWNTO 0);
    VARIABLE add_cast_26 : signed(113 DOWNTO 0);
    VARIABLE add_temp_12 : signed(113 DOWNTO 0);
    VARIABLE add_cast_27 : signed(114 DOWNTO 0);
    VARIABLE mul_temp_14 : signed(98 DOWNTO 0);
    VARIABLE add_cast_28 : signed(114 DOWNTO 0);
    VARIABLE add_temp_13 : signed(114 DOWNTO 0);
    VARIABLE sub_cast_3 : signed(31 DOWNTO 0);
    VARIABLE sub_cast_4 : signed(32 DOWNTO 0);
  BEGIN
    sub_temp := to_signed(0, 68);
    mul_temp := to_signed(0, 99);
    mul_temp_0 := to_signed(0, 99);
    add_temp := to_signed(0, 101);
    mul_temp_1 := to_signed(0, 99);
    add_temp_0 := to_signed(0, 102);
    mul_temp_2 := to_signed(0, 99);
    add_temp_1 := to_signed(0, 103);
    mul_temp_3 := to_signed(0, 99);
    add_temp_2 := to_signed(0, 104);
    mul_temp_4 := to_signed(0, 99);
    add_temp_3 := to_signed(0, 105);
    mul_temp_5 := to_signed(0, 99);
    add_temp_4 := to_signed(0, 106);
    mul_temp_6 := to_signed(0, 99);
    add_temp_5 := to_signed(0, 107);
    mul_temp_7 := to_signed(0, 99);
    add_temp_6 := to_signed(0, 108);
    mul_temp_8 := to_signed(0, 99);
    add_temp_7 := to_signed(0, 109);
    mul_temp_9 := to_signed(0, 99);
    add_temp_8 := to_signed(0, 110);
    mul_temp_10 := to_signed(0, 99);
    add_temp_9 := to_signed(0, 111);
    mul_temp_11 := to_signed(0, 99);
    add_temp_10 := to_signed(0, 112);
    mul_temp_12 := to_signed(0, 99);
    add_temp_11 := to_signed(0, 113);
    mul_temp_13 := to_signed(0, 99);
    add_temp_12 := to_signed(0, 114);
    mul_temp_14 := to_signed(0, 99);
    add_temp_13 := to_signed(0, 115);
    sub_cast := to_signed(0, 67);
    sub_cast_0 := to_signed(0, 68);
    sub_cast_1 := to_signed(0, 68);
    sub_cast_2 := to_signed(0, 33);
    add_cast := to_signed(0, 101);
    add_cast_0 := to_signed(0, 101);
    add_cast_1 := to_signed(0, 102);
    add_cast_2 := to_signed(0, 102);
    add_cast_3 := to_signed(0, 103);
    add_cast_4 := to_signed(0, 103);
    add_cast_5 := to_signed(0, 104);
    add_cast_6 := to_signed(0, 104);
    add_cast_7 := to_signed(0, 105);
    add_cast_8 := to_signed(0, 105);
    add_cast_9 := to_signed(0, 106);
    add_cast_10 := to_signed(0, 106);
    add_cast_11 := to_signed(0, 107);
    add_cast_12 := to_signed(0, 107);
    add_cast_13 := to_signed(0, 108);
    add_cast_14 := to_signed(0, 108);
    add_cast_15 := to_signed(0, 109);
    add_cast_16 := to_signed(0, 109);
    add_cast_17 := to_signed(0, 110);
    add_cast_18 := to_signed(0, 110);
    add_cast_19 := to_signed(0, 111);
    add_cast_20 := to_signed(0, 111);
    add_cast_21 := to_signed(0, 112);
    add_cast_22 := to_signed(0, 112);
    add_cast_23 := to_signed(0, 113);
    add_cast_24 := to_signed(0, 113);
    add_cast_25 := to_signed(0, 114);
    add_cast_26 := to_signed(0, 114);
    add_cast_27 := to_signed(0, 115);
    add_cast_28 := to_signed(0, 115);
    sub_cast_3 := to_signed(0, 32);
    sub_cast_4 := to_signed(0, 33);

    FOR t_1 IN 0 TO 3 LOOP
      FOR t_0 IN 0 TO 3 LOOP
        sub_cast := resize(P_k_signed(t_0, t_1) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 67);
        sub_cast_0 := resize(sub_cast, 68);
        sub_cast_1 := resize(nc(t_0, t_1), 68);
        sub_temp := sub_cast_0 - sub_cast_1;
        IF (sub_temp(67) = '0') AND (sub_temp(66) /= '0') THEN 
          Z(t_0, t_1) := "0111111111111111111111111111111111111111111111111111111111111111111";
        ELSIF (sub_temp(67) = '1') AND (sub_temp(66) /= '1') THEN 
          Z(t_0, t_1) := "1000000000000000000000000000000000000000000000000000000000000000000";
        ELSE 
          Z(t_0, t_1) := sub_temp(66 DOWNTO 0);
        END IF;
      END LOOP;
    END LOOP;
    FOR t_3 IN 0 TO 3 LOOP
      FOR t_2 IN 0 TO 3 LOOP
        sub_cast_2 := resize(C_signed(t_2, t_3), 33);
        mul_temp := T1_signed(t_2, t_3) * Z(0, 0);
        add_cast := resize(mul_temp, 101);
        mul_temp_0 := T2_signed(t_2, t_3) * Z(0, 1);
        add_cast_0 := resize(mul_temp_0, 101);
        add_temp := add_cast + add_cast_0;
        add_cast_1 := resize(add_temp, 102);
        mul_temp_1 := T3_signed(t_2, t_3) * Z(0, 2);
        add_cast_2 := resize(mul_temp_1, 102);
        add_temp_0 := add_cast_1 + add_cast_2;
        add_cast_3 := resize(add_temp_0, 103);
        mul_temp_2 := T4_signed(t_2, t_3) * Z(0, 3);
        add_cast_4 := resize(mul_temp_2, 103);
        add_temp_1 := add_cast_3 + add_cast_4;
        add_cast_5 := resize(add_temp_1, 104);
        mul_temp_3 := T5_signed(t_2, t_3) * Z(1, 0);
        add_cast_6 := resize(mul_temp_3, 104);
        add_temp_2 := add_cast_5 + add_cast_6;
        add_cast_7 := resize(add_temp_2, 105);
        mul_temp_4 := T6_signed(t_2, t_3) * Z(1, 1);
        add_cast_8 := resize(mul_temp_4, 105);
        add_temp_3 := add_cast_7 + add_cast_8;
        add_cast_9 := resize(add_temp_3, 106);
        mul_temp_5 := T7_signed(t_2, t_3) * Z(1, 2);
        add_cast_10 := resize(mul_temp_5, 106);
        add_temp_4 := add_cast_9 + add_cast_10;
        add_cast_11 := resize(add_temp_4, 107);
        mul_temp_6 := T8_signed(t_2, t_3) * Z(1, 3);
        add_cast_12 := resize(mul_temp_6, 107);
        add_temp_5 := add_cast_11 + add_cast_12;
        add_cast_13 := resize(add_temp_5, 108);
        mul_temp_7 := T9_signed(t_2, t_3) * Z(2, 0);
        add_cast_14 := resize(mul_temp_7, 108);
        add_temp_6 := add_cast_13 + add_cast_14;
        add_cast_15 := resize(add_temp_6, 109);
        mul_temp_8 := T10_signed(t_2, t_3) * Z(2, 1);
        add_cast_16 := resize(mul_temp_8, 109);
        add_temp_7 := add_cast_15 + add_cast_16;
        add_cast_17 := resize(add_temp_7, 110);
        mul_temp_9 := T11_signed(t_2, t_3) * Z(2, 2);
        add_cast_18 := resize(mul_temp_9, 110);
        add_temp_8 := add_cast_17 + add_cast_18;
        add_cast_19 := resize(add_temp_8, 111);
        mul_temp_10 := T12_signed(t_2, t_3) * Z(2, 3);
        add_cast_20 := resize(mul_temp_10, 111);
        add_temp_9 := add_cast_19 + add_cast_20;
        add_cast_21 := resize(add_temp_9, 112);
        mul_temp_11 := T13_signed(t_2, t_3) * Z(3, 0);
        add_cast_22 := resize(mul_temp_11, 112);
        add_temp_10 := add_cast_21 + add_cast_22;
        add_cast_23 := resize(add_temp_10, 113);
        mul_temp_12 := T14_signed(t_2, t_3) * Z(3, 1);
        add_cast_24 := resize(mul_temp_12, 113);
        add_temp_11 := add_cast_23 + add_cast_24;
        add_cast_25 := resize(add_temp_11, 114);
        mul_temp_13 := T15_signed(t_2, t_3) * Z(3, 2);
        add_cast_26 := resize(mul_temp_13, 114);
        add_temp_12 := add_cast_25 + add_cast_26;
        add_cast_27 := resize(add_temp_12, 115);
        mul_temp_14 := T16_signed(t_2, t_3) * Z(3, 3);
        add_cast_28 := resize(mul_temp_14, 115);
        add_temp_13 := add_cast_27 + add_cast_28;
        IF ((add_temp_13(114) = '0') AND (add_temp_13(113 DOWNTO 71) /= "0000000000000000000000000000000000000000000")) OR ((add_temp_13(114) = '0') AND (add_temp_13(71 DOWNTO 40) = X"7FFFFFFF")) THEN 
          sub_cast_3 := X"7FFFFFFF";
        ELSIF (add_temp_13(114) = '1') AND (add_temp_13(113 DOWNTO 71) /= "1111111111111111111111111111111111111111111") THEN 
          sub_cast_3 := X"80000000";
        ELSE 
          sub_cast_3 := add_temp_13(71 DOWNTO 40) + ('0' & add_temp_13(39));
        END IF;
        sub_cast_4 := resize(sub_cast_3, 33);
        S_k_inv_tmp(t_2, t_3) <= sub_cast_2 - sub_cast_4;
      END LOOP;
    END LOOP;

  END PROCESS Inverse_aprox_1_output;


  outputgen: FOR k IN 0 TO 3 GENERATE
    outputgen1: FOR k1 IN 0 TO 3 GENERATE
      S_k_inv(k, k1) <= std_logic_vector(S_k_inv_tmp(k, k1));
    END GENERATE;
  END GENERATE;

END rtl;

