-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\EkalmanF_ac_sim\MATLAB_Function.vhd
-- Created: 2026-01-10 22:56:30
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: EkalmanF_ac_sim/EKF/MATLAB Function
-- Hierarchy Level: 1
-- Model version: 1.68
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.EKF_pkg.ALL;

ENTITY MATLAB_Function IS
  PORT( xkk                               :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
        Jacobs                            :   OUT   matrix_of_std_logic_vector32(0 TO 3, 0 TO 3)  -- sfix32_En20 [4x4]
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

  -- Signals
  SIGNAL xkk_signed                       : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Jacobs_tmp                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]

BEGIN
  outputgen2: FOR k IN 0 TO 3 GENERATE
    xkk_signed(k) <= signed(xkk(k));
  END GENERATE;

  MATLAB_Function_1_output : PROCESS (xkk_signed)
    VARIABLE term1 : signed(193 DOWNTO 0);
    VARIABLE term2 : signed(193 DOWNTO 0);
    VARIABLE xkk1 : vector_of_signed32(0 TO 3);
    VARIABLE theta2 : signed(63 DOWNTO 0);
    VARIABLE theta4 : signed(127 DOWNTO 0);
    VARIABLE theta2_0 : signed(63 DOWNTO 0);
    VARIABLE theta4_0 : signed(127 DOWNTO 0);
    VARIABLE sub_cast : signed(95 DOWNTO 0);
    VARIABLE sub_cast_0 : signed(96 DOWNTO 0);
    VARIABLE sub_temp : signed(96 DOWNTO 0);
    VARIABLE add_cast : signed(160 DOWNTO 0);
    VARIABLE mul_temp : signed(159 DOWNTO 0);
    VARIABLE add_cast_0 : signed(160 DOWNTO 0);
    VARIABLE add_temp : signed(160 DOWNTO 0);
    VARIABLE mul_temp_0 : signed(192 DOWNTO 0);
    VARIABLE add_cast_1 : signed(193 DOWNTO 0);
    VARIABLE sub_cast_1 : signed(95 DOWNTO 0);
    VARIABLE sub_cast_2 : signed(96 DOWNTO 0);
    VARIABLE sub_temp_0 : signed(96 DOWNTO 0);
    VARIABLE add_cast_2 : signed(160 DOWNTO 0);
    VARIABLE mul_temp_1 : signed(159 DOWNTO 0);
    VARIABLE add_cast_3 : signed(160 DOWNTO 0);
    VARIABLE add_temp_0 : signed(160 DOWNTO 0);
    VARIABLE mul_temp_2 : signed(192 DOWNTO 0);
    VARIABLE add_cast_4 : signed(193 DOWNTO 0);
  BEGIN
    -- 1. Math Rules (Keep 'Zero' rounding)
    -- 2. Pre-allocate output

    FOR t_0 IN 0 TO 3 LOOP
      xkk1(t_0) := xkk_signed(t_0);

      FOR t_1 IN 0 TO 3 LOOP
        Jacobs_tmp(t_1, t_0) <= to_signed(0, 32);
      END LOOP;

    END LOOP;

    -- 3. Constants
    -- 4. Calculate terms using our CUSTOM approximation function
    -- This bypasses the built-in 'cos' and its division logic entirely.
    -- --- SUB-FUNCTION: Hardware Friendly Cosine ---
    -- 4th-Order Taylor Series: 1 - x^2/2 + x^4/24
    -- Valid for range: -pi/2 to +pi/2
    -- Uses only MULT and ADD (No Division!)
    -- Define coefficients with same type as input
    -- 1/2
    -- 1/24
    -- Calculations
    theta2 := xkk1(0) * xkk1(0);
    -- x^2
    theta4 := theta2 * theta2;
    -- x^4
    -- Result: 1 - 0.5*x^2 + 0.0416*x^4
    sub_cast := resize(theta2 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
    sub_cast_0 := resize(sub_cast, 97);
    sub_temp := signed'("0000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000") - sub_cast_0;
    add_cast := resize(sub_temp & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 161);
    mul_temp := to_signed(43690, 32) * theta4;
    add_cast_0 := resize(mul_temp, 161);
    add_temp := add_cast + add_cast_0;
    mul_temp_0 := to_signed(314572, 32) * add_temp;
    add_cast_1 := resize(mul_temp_0, 194);
    term1 := add_cast_1 + signed'("00000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
    -- --- SUB-FUNCTION: Hardware Friendly Cosine ---
    -- 4th-Order Taylor Series: 1 - x^2/2 + x^4/24
    -- Valid for range: -pi/2 to +pi/2
    -- Uses only MULT and ADD (No Division!)
    -- Define coefficients with same type as input
    -- 1/2
    -- 1/24
    -- Calculations
    theta2_0 := xkk1(1) * xkk1(1);
    -- x^2
    theta4_0 := theta2_0 * theta2_0;
    -- x^4
    -- Result: 1 - 0.5*x^2 + 0.0416*x^4
    sub_cast_1 := resize(theta2_0 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
    sub_cast_2 := resize(sub_cast_1, 97);
    sub_temp_0 := signed'("0000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000") - sub_cast_2;
    add_cast_2 := resize(sub_temp_0 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 161);
    mul_temp_1 := to_signed(43690, 32) * theta4_0;
    add_cast_3 := resize(mul_temp_1, 161);
    add_temp_0 := add_cast_2 + add_cast_3;
    mul_temp_2 := to_signed(314572, 32) * add_temp_0;
    add_cast_4 := resize(mul_temp_2, 194);
    term2 := add_cast_4 + signed'("00000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
    -- 5. Assign
    Jacobs_tmp(0, 0) <= term1(131 DOWNTO 100) + ('0' & (term1(193) AND (term1(99) OR term1(98) OR term1(97) OR term1(96) OR term1(95) OR term1(94) OR term1(93) OR term1(92) OR term1(91) OR term1(90) OR term1(89) OR term1(88) OR term1(87) OR term1(86) OR term1(85) OR term1(84) OR term1(83) OR term1(82) OR term1(81) OR term1(80) OR term1(79) OR term1(78) OR term1(77) OR term1(76) OR term1(75) OR term1(74) OR term1(73) OR term1(72) OR term1(71) OR term1(70) OR term1(69) OR term1(68) OR term1(67) OR term1(66) OR term1(65) OR term1(64) OR term1(63) OR term1(62) OR term1(61) OR term1(60) OR term1(59) OR term1(58) OR term1(57) OR term1(56) OR term1(55) OR term1(54) OR term1(53) OR term1(52) OR term1(51) OR term1(50) OR term1(49) OR term1(48) OR term1(47) OR term1(46) OR term1(45) OR term1(44) OR term1(43) OR term1(42) OR term1(41) OR term1(40) OR term1(39) OR term1(38) OR term1(37) OR term1(36) OR term1(35) OR term1(34) OR term1(33) OR term1(32) OR term1(31) OR term1(30) OR term1(29) OR term1(28) OR term1(27) OR term1(26) OR term1(25) OR term1(24) OR term1(23) OR term1(22) OR term1(21) OR term1(20) OR term1(19) OR term1(18) OR term1(17) OR term1(16) OR term1(15) OR term1(14) OR term1(13) OR term1(12) OR term1(11) OR term1(10) OR term1(9) OR term1(8) OR term1(7) OR term1(6) OR term1(5) OR term1(4) OR term1(3) OR term1(2) OR term1(1) OR term1(0))));
    Jacobs_tmp(0, 2) <= to_signed(20971, 32);
    Jacobs_tmp(1, 1) <= term2(131 DOWNTO 100) + ('0' & (term2(193) AND (term2(99) OR term2(98) OR term2(97) OR term2(96) OR term2(95) OR term2(94) OR term2(93) OR term2(92) OR term2(91) OR term2(90) OR term2(89) OR term2(88) OR term2(87) OR term2(86) OR term2(85) OR term2(84) OR term2(83) OR term2(82) OR term2(81) OR term2(80) OR term2(79) OR term2(78) OR term2(77) OR term2(76) OR term2(75) OR term2(74) OR term2(73) OR term2(72) OR term2(71) OR term2(70) OR term2(69) OR term2(68) OR term2(67) OR term2(66) OR term2(65) OR term2(64) OR term2(63) OR term2(62) OR term2(61) OR term2(60) OR term2(59) OR term2(58) OR term2(57) OR term2(56) OR term2(55) OR term2(54) OR term2(53) OR term2(52) OR term2(51) OR term2(50) OR term2(49) OR term2(48) OR term2(47) OR term2(46) OR term2(45) OR term2(44) OR term2(43) OR term2(42) OR term2(41) OR term2(40) OR term2(39) OR term2(38) OR term2(37) OR term2(36) OR term2(35) OR term2(34) OR term2(33) OR term2(32) OR term2(31) OR term2(30) OR term2(29) OR term2(28) OR term2(27) OR term2(26) OR term2(25) OR term2(24) OR term2(23) OR term2(22) OR term2(21) OR term2(20) OR term2(19) OR term2(18) OR term2(17) OR term2(16) OR term2(15) OR term2(14) OR term2(13) OR term2(12) OR term2(11) OR term2(10) OR term2(9) OR term2(8) OR term2(7) OR term2(6) OR term2(5) OR term2(4) OR term2(3) OR term2(2) OR term2(1) OR term2(0))));
    Jacobs_tmp(1, 3) <= to_signed(20971, 32);
    Jacobs_tmp(2, 2) <= to_signed(1048576, 32);
    Jacobs_tmp(3, 3) <= to_signed(1048576, 32);
  END PROCESS MATLAB_Function_1_output;


  outputgen: FOR k IN 0 TO 3 GENERATE
    outputgen1: FOR k1 IN 0 TO 3 GENERATE
      Jacobs(k, k1) <= std_logic_vector(Jacobs_tmp(k, k1));
    END GENERATE;
  END GENERATE;

END rtl;

