-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\EkalmanF_ac_sim\Predict.vhd
-- Created: 2026-01-12 14:16:47
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Predict
-- Source Path: EkalmanF_ac_sim/EKF/Predict
-- Hierarchy Level: 1
-- Model version: 1.76
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.EKF_pkg.ALL;

ENTITY Predict IS
  PORT( u_k                               :   IN    vector_of_std_logic_vector32(0 TO 1);  -- sfix32_En20 [2]
        x_k_1_k_1                         :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
        P_k_1_k_1                         :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        F                                 :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        Q                                 :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        B                                 :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 1);  -- sfix32_En20 [4x2]
        x_k_k_1                           :   OUT   vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
        P_k_k_1                           :   OUT   matrix_of_std_logic_vector32(0 TO 3, 0 TO 3)  -- sfix32_En20 [4x4]
        );
END Predict;


ARCHITECTURE rtl OF Predict IS

  -- Component Declarations
  COMPONENT MATLAB_Function
    PORT( x_est                           :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
          dt                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En20
          fx                              :   OUT   vector_of_std_logic_vector32(0 TO 3)  -- sfix32_En20 [4]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MATLAB_Function
    USE ENTITY work.MATLAB_Function(rtl);

  -- Constants
  CONSTANT select_indices0_data           : vector_of_signed8(0 TO 7) := 
    (to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#03#, 8),
     to_signed(16#07#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8));  -- int8 [8]
  CONSTANT select_indices1_data           : vector_of_signed8(0 TO 7) := 
    (to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#01#, 8),
     to_signed(16#02#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8));  -- int8 [8]
  CONSTANT select_indices0_data_2         : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8),
     to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8),
     to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8),
     to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8),
     to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8),
     to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8),
     to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8),
     to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8),
     to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8),
     to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8),
     to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8),
     to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8),
     to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8));  -- int8 [64]
  CONSTANT select_indices1_data_2         : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8),
     to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8),
     to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8),
     to_signed(16#04#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8),
     to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8),
     to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8),
     to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8),
     to_signed(16#0C#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8),
     to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#09#, 8),
     to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8),
     to_signed(16#0F#, 8), to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8),
     to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8),
     to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8));  -- int8 [64]
  CONSTANT select_indices0_data_4         : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8),
     to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8),
     to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8),
     to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8),
     to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8),
     to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8),
     to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8),
     to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8),
     to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8),
     to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8),
     to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8),
     to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8),
     to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8));  -- int8 [64]
  CONSTANT select_indices1_data_4         : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8),
     to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8),
     to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8),
     to_signed(16#04#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8),
     to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8),
     to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8),
     to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8),
     to_signed(16#0C#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8),
     to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#09#, 8),
     to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8),
     to_signed(16#0F#, 8), to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8),
     to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8),
     to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8));  -- int8 [64]

  -- Signals
  SIGNAL B_signed                         : matrix_of_signed32(0 TO 3, 0 TO 1);  -- sfix32_En20 [4x2]
  SIGNAL s                                : vector_of_signed32(0 TO 7);  -- sfix32_En20 [8]
  SIGNAL selector_out                     : vector_of_signed32(0 TO 7);  -- sfix32_En20 [8]
  SIGNAL s_1                              : vector_of_signed32(0 TO 7);  -- sfix32_En20 [8]
  SIGNAL u_k_signed                       : vector_of_signed32(0 TO 1);  -- sfix32_En20 [2]
  SIGNAL selector_out_1                   : vector_of_signed32(0 TO 7);  -- sfix32_En20 [8]
  SIGNAL s_2                              : vector_of_signed32(0 TO 7);  -- sfix32_En20 [8]
  SIGNAL MMul_dot_product_out             : vector_of_signed64(0 TO 7);  -- sfix64_En40 [8]
  SIGNAL reshape_out                      : matrix_of_signed64(0 TO 1, 0 TO 3);  -- sfix64_En40 [2x4]
  SIGNAL selector_out_2                   : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL Constant_out1                    : signed(31 DOWNTO 0);  -- sfix32_En20
  SIGNAL selector_out_3                   : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL s_3                              : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL MatrixMultiply_out1              : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL fx                               : vector_of_std_logic_vector32(0 TO 3);  -- ufix32 [4]
  SIGNAL fx_signed                        : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Add_add_cast                     : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL Add_out1                         : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL Data_Type_Conversion_out1        : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL F_signed                         : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL s_4                              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out_4                   : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL s_5                              : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL P_k_1_k_1_signed                 : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL s_6                              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out_5                   : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL s_7                              : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL MMul_dot_product_out_1           : vector_of_signed64(0 TO 63);  -- sfix64_En40 [64]
  SIGNAL reshape_out_1                    : matrix_of_signed64(0 TO 3, 0 TO 15);  -- sfix64_En40 [4x16]
  SIGNAL selector_out_6                   : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL selector_out_7                   : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL MMul_add_01_out                  : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL selector_out_8                   : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL MMul_add_12_out                  : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL selector_out_9                   : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL s_8                              : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL selector_out_10                  : vector_of_signed64(0 TO 63);  -- sfix64_En40 [64]
  SIGNAL s_9                              : vector_of_signed64(0 TO 63);  -- sfix64_En40 [64]
  SIGNAL F_signed_1                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL Transpose_out1                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL s_10                             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out_11                  : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL s_11                             : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL MMul_dot_product_out_2           : vector_of_signed96(0 TO 63);  -- sfix96_En60 [64]
  SIGNAL reshape_out_2                    : matrix_of_signed96(0 TO 3, 0 TO 15);  -- sfix96_En60 [4x16]
  SIGNAL selector_out_12                  : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL selector_out_13                  : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL MMul_add_01_out_1                : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL selector_out_14                  : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL MMul_add_12_out_1                : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL selector_out_15                  : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL s_12                             : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL Product2_out1                    : matrix_of_signed96(0 TO 3, 0 TO 3);  -- sfix96_En60 [4x4]
  SIGNAL c23_Product2_out1                : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL Q_signed                         : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL c23_Q                            : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Add1_add_cast                    : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL c23_Add1_out1                    : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL c27_Data_Type_Conversion1_out1   : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Data_Type_Conversion1_out1       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]

BEGIN
  u_MATLAB_Function : MATLAB_Function
    PORT MAP( x_est => x_k_1_k_1,  -- sfix32_En20 [4]
              dt => std_logic_vector(Constant_out1),  -- sfix32_En20
              fx => fx  -- sfix32_En20 [4]
              );

  outputgen13: FOR k IN 0 TO 3 GENERATE
    outputgen14: FOR k1 IN 0 TO 1 GENERATE
      B_signed(k, k1) <= signed(B(k, k1));
    END GENERATE;
  END GENERATE;

  s_gen1: FOR d1 IN 0 TO 1 GENERATE
    s_gen: FOR d0 IN 0 TO 3 GENERATE
      s(d0 + (d1 * 4)) <= B_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_gen: FOR ii_select IN 0 TO 7 GENERATE
    selector_out(ii_select) <= s(to_integer(resize(select_indices0_data(ii_select), 32) - 1));
  END GENERATE selector_out_gen;


  s_1_gen: FOR d0 IN 0 TO 7 GENERATE
    s_1(d0) <= selector_out(d0);
  END GENERATE;

  outputgen12: FOR k IN 0 TO 1 GENERATE
    u_k_signed(k) <= signed(u_k(k));
  END GENERATE;


  selector_out_1_gen: FOR ii_select1 IN 0 TO 7 GENERATE
    selector_out_1(ii_select1) <= u_k_signed(to_integer(resize(select_indices1_data(ii_select1), 32) - 1));
  END GENERATE selector_out_1_gen;


  s_2_gen: FOR d0 IN 0 TO 7 GENERATE
    s_2(d0) <= selector_out_1(d0);
  END GENERATE;


  MMul_dot_product_out_gen: FOR t_0 IN 0 TO 7 GENERATE
    MMul_dot_product_out(t_0) <= s_1(t_0) * s_2(t_0);
  END GENERATE MMul_dot_product_out_gen;


  reshape_out_gen1: FOR d1 IN 0 TO 3 GENERATE
    reshape_out_gen: FOR d0 IN 0 TO 1 GENERATE
      reshape_out(d0, d1) <= MMul_dot_product_out(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;


  selector_out_2_gen: FOR t_01 IN 0 TO 3 GENERATE
    selector_out_2(t_01) <= reshape_out(0, t_01);
  END GENERATE selector_out_2_gen;


  Constant_out1 <= to_signed(20972, 32);


  selector_out_3_gen: FOR t_02 IN 0 TO 3 GENERATE
    selector_out_3(t_02) <= reshape_out(1, t_02);
  END GENERATE selector_out_3_gen;



  s_3_gen: FOR t_03 IN 0 TO 3 GENERATE
    s_3(t_03) <= selector_out_2(t_03) + selector_out_3(t_03);
  END GENERATE s_3_gen;


  MatrixMultiply_out1_gen: FOR d0 IN 0 TO 3 GENERATE
    MatrixMultiply_out1(d0) <= s_3(d0);
  END GENERATE;

  outputgen11: FOR k IN 0 TO 3 GENERATE
    fx_signed(k) <= signed(fx(k));
  END GENERATE;


  Add_out1_gen: FOR t_04 IN 0 TO 3 GENERATE
    Add_add_cast(t_04) <= resize(fx_signed(t_04) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);
    Add_out1(t_04) <= MatrixMultiply_out1(t_04) + Add_add_cast(t_04);
  END GENERATE Add_out1_gen;



  Data_Type_Conversion_out1_gen: FOR ii IN 0 TO 3 GENERATE
    Data_Type_Conversion_out1(ii) <= Add_out1(ii)(51 DOWNTO 20);
  END GENERATE Data_Type_Conversion_out1_gen;


  outputgen10: FOR k IN 0 TO 3 GENERATE
    x_k_k_1(k) <= std_logic_vector(Data_Type_Conversion_out1(k));
  END GENERATE;

  outputgen8: FOR k IN 0 TO 3 GENERATE
    outputgen9: FOR k1 IN 0 TO 3 GENERATE
      F_signed(k, k1) <= signed(F(k, k1));
    END GENERATE;
  END GENERATE;

  s_4_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_4_gen: FOR d0 IN 0 TO 3 GENERATE
      s_4(d0 + (d1 * 4)) <= F_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_4_gen: FOR ii_select2 IN 0 TO 63 GENERATE
    selector_out_4(ii_select2) <= s_4(to_integer(resize(select_indices0_data_2(ii_select2), 32) - 1));
  END GENERATE selector_out_4_gen;


  s_5_gen: FOR d0 IN 0 TO 63 GENERATE
    s_5(d0) <= selector_out_4(d0);
  END GENERATE;

  outputgen6: FOR k IN 0 TO 3 GENERATE
    outputgen7: FOR k1 IN 0 TO 3 GENERATE
      P_k_1_k_1_signed(k, k1) <= signed(P_k_1_k_1(k, k1));
    END GENERATE;
  END GENERATE;

  s_6_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_6_gen: FOR d0 IN 0 TO 3 GENERATE
      s_6(d0 + (d1 * 4)) <= P_k_1_k_1_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_5_gen: FOR ii_select3 IN 0 TO 63 GENERATE
    selector_out_5(ii_select3) <= s_6(to_integer(resize(select_indices1_data_2(ii_select3), 32) - 1));
  END GENERATE selector_out_5_gen;


  s_7_gen: FOR d0 IN 0 TO 63 GENERATE
    s_7(d0) <= selector_out_5(d0);
  END GENERATE;


  MMul_dot_product_out_1_gen: FOR t_05 IN 0 TO 63 GENERATE
    MMul_dot_product_out_1(t_05) <= s_5(t_05) * s_7(t_05);
  END GENERATE MMul_dot_product_out_1_gen;


  reshape_out_1_gen1: FOR d1 IN 0 TO 15 GENERATE
    reshape_out_1_gen: FOR d0 IN 0 TO 3 GENERATE
      reshape_out_1(d0, d1) <= MMul_dot_product_out_1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;


  selector_out_6_gen: FOR t_06 IN 0 TO 15 GENERATE
    selector_out_6(t_06) <= reshape_out_1(0, t_06);
  END GENERATE selector_out_6_gen;



  selector_out_7_gen: FOR t_07 IN 0 TO 15 GENERATE
    selector_out_7(t_07) <= reshape_out_1(1, t_07);
  END GENERATE selector_out_7_gen;



  MMul_add_01_out_gen: FOR t_08 IN 0 TO 15 GENERATE
    MMul_add_01_out(t_08) <= selector_out_6(t_08) + selector_out_7(t_08);
  END GENERATE MMul_add_01_out_gen;



  selector_out_8_gen: FOR t_09 IN 0 TO 15 GENERATE
    selector_out_8(t_09) <= reshape_out_1(2, t_09);
  END GENERATE selector_out_8_gen;



  MMul_add_12_out_gen: FOR t_010 IN 0 TO 15 GENERATE
    MMul_add_12_out(t_010) <= MMul_add_01_out(t_010) + selector_out_8(t_010);
  END GENERATE MMul_add_12_out_gen;



  selector_out_9_gen: FOR t_011 IN 0 TO 15 GENERATE
    selector_out_9(t_011) <= reshape_out_1(3, t_011);
  END GENERATE selector_out_9_gen;



  s_8_gen: FOR t_012 IN 0 TO 15 GENERATE
    s_8(t_012) <= MMul_add_12_out(t_012) + selector_out_9(t_012);
  END GENERATE s_8_gen;



  selector_out_10_gen: FOR ii_select4 IN 0 TO 63 GENERATE
    selector_out_10(ii_select4) <= s_8(to_integer(resize(select_indices0_data_4(ii_select4), 32) - 1));
  END GENERATE selector_out_10_gen;


  s_9_gen: FOR d0 IN 0 TO 63 GENERATE
    s_9(d0) <= selector_out_10(d0);
  END GENERATE;

  outputgen4: FOR k IN 0 TO 3 GENERATE
    outputgen5: FOR k1 IN 0 TO 3 GENERATE
      F_signed_1(k, k1) <= signed(F(k, k1));
    END GENERATE;
  END GENERATE;


  Transpose_out1_gen: FOR t_1 IN 0 TO 3 GENERATE
    Transpose_out1_gen_1: FOR t_013 IN 0 TO 3 GENERATE
      Transpose_out1(t_013, t_1) <= F_signed_1(t_1, t_013);
    END GENERATE Transpose_out1_gen_1;
  END GENERATE Transpose_out1_gen;


  s_10_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_10_gen: FOR d0 IN 0 TO 3 GENERATE
      s_10(d0 + (d1 * 4)) <= Transpose_out1(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_11_gen: FOR ii_select5 IN 0 TO 63 GENERATE
    selector_out_11(ii_select5) <= s_10(to_integer(resize(select_indices1_data_4(ii_select5), 32) - 1));
  END GENERATE selector_out_11_gen;


  s_11_gen: FOR d0 IN 0 TO 63 GENERATE
    s_11(d0) <= selector_out_11(d0);
  END GENERATE;


  MMul_dot_product_out_2_gen: FOR t_014 IN 0 TO 63 GENERATE
    MMul_dot_product_out_2(t_014) <= s_9(t_014) * s_11(t_014);
  END GENERATE MMul_dot_product_out_2_gen;


  reshape_out_2_gen1: FOR d1 IN 0 TO 15 GENERATE
    reshape_out_2_gen: FOR d0 IN 0 TO 3 GENERATE
      reshape_out_2(d0, d1) <= MMul_dot_product_out_2(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;


  selector_out_12_gen: FOR t_015 IN 0 TO 15 GENERATE
    selector_out_12(t_015) <= reshape_out_2(0, t_015);
  END GENERATE selector_out_12_gen;



  selector_out_13_gen: FOR t_016 IN 0 TO 15 GENERATE
    selector_out_13(t_016) <= reshape_out_2(1, t_016);
  END GENERATE selector_out_13_gen;



  MMul_add_01_out_1_gen: FOR t_017 IN 0 TO 15 GENERATE
    MMul_add_01_out_1(t_017) <= selector_out_12(t_017) + selector_out_13(t_017);
  END GENERATE MMul_add_01_out_1_gen;



  selector_out_14_gen: FOR t_018 IN 0 TO 15 GENERATE
    selector_out_14(t_018) <= reshape_out_2(2, t_018);
  END GENERATE selector_out_14_gen;



  MMul_add_12_out_1_gen: FOR t_019 IN 0 TO 15 GENERATE
    MMul_add_12_out_1(t_019) <= MMul_add_01_out_1(t_019) + selector_out_14(t_019);
  END GENERATE MMul_add_12_out_1_gen;



  selector_out_15_gen: FOR t_020 IN 0 TO 15 GENERATE
    selector_out_15(t_020) <= reshape_out_2(3, t_020);
  END GENERATE selector_out_15_gen;



  s_12_gen: FOR t_021 IN 0 TO 15 GENERATE
    s_12(t_021) <= MMul_add_12_out_1(t_021) + selector_out_15(t_021);
  END GENERATE s_12_gen;


  Product2_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Product2_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Product2_out1(d0, d1) <= s_12(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c23_Product2_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c23_Product2_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c23_Product2_out1(d0 + (d1 * 4)) <= Product2_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  outputgen2: FOR k IN 0 TO 3 GENERATE
    outputgen3: FOR k1 IN 0 TO 3 GENERATE
      Q_signed(k, k1) <= signed(Q(k, k1));
    END GENERATE;
  END GENERATE;

  c23_Q_gen1: FOR d1 IN 0 TO 3 GENERATE
    c23_Q_gen: FOR d0 IN 0 TO 3 GENERATE
      c23_Q(d0 + (d1 * 4)) <= Q_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  c23_Add1_out1_gen: FOR t_022 IN 0 TO 15 GENERATE
    Add1_add_cast(t_022) <= resize(c23_Q(t_022) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
    c23_Add1_out1(t_022) <= c23_Product2_out1(t_022) + Add1_add_cast(t_022);
  END GENERATE c23_Add1_out1_gen;



  c27_Data_Type_Conversion1_out1_gen: FOR ii1 IN 0 TO 15 GENERATE
    c27_Data_Type_Conversion1_out1(ii1) <= c23_Add1_out1(ii1)(71 DOWNTO 40);
  END GENERATE c27_Data_Type_Conversion1_out1_gen;


  Data_Type_Conversion1_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Data_Type_Conversion1_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Data_Type_Conversion1_out1(d0, d1) <= c27_Data_Type_Conversion1_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen: FOR k IN 0 TO 3 GENERATE
    outputgen1: FOR k1 IN 0 TO 3 GENERATE
      P_k_k_1(k, k1) <= std_logic_vector(Data_Type_Conversion1_out1(k, k1));
    END GENERATE;
  END GENERATE;

END rtl;

