-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\kalman_ac_sim\Kalman_Gain_Calculation.vhd
-- Created: 2026-01-10 22:53:45
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Kalman_Gain_Calculation
-- Source Path: kalman_ac_sim/Kalman DUT/Kalman Gain Calculation
-- Hierarchy Level: 1
-- Model version: 1.65
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Kalman_DUT_pkg.ALL;

ENTITY Kalman_Gain_Calculation IS
  PORT( P_k_k_1                           :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        H                                 :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        C                                 :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T1                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T2                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T3                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T4                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T5                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T6                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T7                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T8                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T9                                :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T10                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T11                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T12                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T13                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T14                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T15                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        T16                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        K_k                               :   OUT   matrix_of_std_logic_vector32(0 TO 3, 0 TO 3)  -- sfix32_En20 [4x4]
        );
END Kalman_Gain_Calculation;


ARCHITECTURE rtl OF Kalman_Gain_Calculation IS

  -- Component Declarations
  COMPONENT Inverse_aprox
    PORT( P_k                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          C                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T1                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T2                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T3                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T4                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T5                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T6                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T7                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T8                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T9                              :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T10                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T11                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T12                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T13                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T14                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T15                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          T16                             :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
          S_k_inv                         :   OUT   matrix_of_std_logic_vector33(0 TO 3, 0 TO 3)  -- sfix33_En20 [4x4]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Inverse_aprox
    USE ENTITY work.Inverse_aprox(rtl);

  -- Constants
  CONSTANT select_indices0_data           : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8),
     to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8),
     to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8),
     to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8),
     to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8),
     to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8),
     to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8),
     to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8),
     to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8),
     to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8),
     to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8),
     to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8),
     to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8));  -- int8 [64]
  CONSTANT select_indices1_data           : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8),
     to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8),
     to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8),
     to_signed(16#04#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8),
     to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8),
     to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8),
     to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8),
     to_signed(16#0C#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8),
     to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#09#, 8),
     to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8),
     to_signed(16#0F#, 8), to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8),
     to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8),
     to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8));  -- int8 [64]
  CONSTANT select_indices01_data          : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8),
     to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8),
     to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8),
     to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8),
     to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8),
     to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8),
     to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8),
     to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8),
     to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8),
     to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8),
     to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8),
     to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8),
     to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8));  -- int8 [64]
  CONSTANT select_indices11_data          : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8),
     to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8),
     to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8),
     to_signed(16#04#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8),
     to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8),
     to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8),
     to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8),
     to_signed(16#0C#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8),
     to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#09#, 8),
     to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8),
     to_signed(16#0F#, 8), to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8),
     to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8),
     to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8));  -- int8 [64]

  -- Signals
  SIGNAL P_k_k_1_signed                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL s                                : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out                     : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL s_1                              : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL H_signed                         : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL Transpose_out1                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL s_2                              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out_1                   : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL s_3                              : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL MMul_dot_product_out             : vector_of_signed64(0 TO 63);  -- sfix64_En40 [64]
  SIGNAL reshape_out                      : matrix_of_signed64(0 TO 3, 0 TO 15);  -- sfix64_En40 [4x16]
  SIGNAL selector_out_2                   : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL selector_out_3                   : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL MMul_add_01_out                  : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL selector_out_4                   : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL MMul_add_12_out                  : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL selector_out_5                   : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL s_4                              : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL selector_out_6                   : vector_of_signed64(0 TO 63);  -- sfix64_En40 [64]
  SIGNAL s_5                              : vector_of_signed64(0 TO 63);  -- sfix64_En40 [64]
  SIGNAL S_k_inv                          : matrix_of_std_logic_vector33(0 TO 3, 0 TO 3);  -- ufix33 [4x4]
  SIGNAL S_k_inv_signed                   : matrix_of_signed33(0 TO 3, 0 TO 3);  -- sfix33_En20 [4x4]
  SIGNAL c13_S_k_inv                      : vector_of_signed33(0 TO 15);  -- sfix33_En20 [16]
  SIGNAL c13_Data_Type_Conversion1_out1   : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Data_Type_Conversion1_out1       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL s_6                              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out_7                   : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL s_7                              : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL MMul_dot_product_out_1           : vector_of_signed96(0 TO 63);  -- sfix96_En60 [64]
  SIGNAL reshape_out_1                    : matrix_of_signed96(0 TO 3, 0 TO 15);  -- sfix96_En60 [4x16]
  SIGNAL selector_out_8                   : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL selector_out_9                   : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL MMul_add_01_out_1                : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL selector_out_10                  : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL MMul_add_12_out_1                : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL selector_out_11                  : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL s_8                              : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL Product2_out1                    : matrix_of_signed96(0 TO 3, 0 TO 3);  -- sfix96_En60 [4x4]
  SIGNAL c15_Product2_out1                : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL c15_Data_Type_Conversion2_out1   : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Data_Type_Conversion2_out1       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]

BEGIN
  u_Inverse_aprox : Inverse_aprox
    PORT MAP( P_k => P_k_k_1,  -- sfix32_En20 [4x4]
              C => C,  -- sfix32_En20 [4x4]
              T1 => T1,  -- sfix32_En20 [4x4]
              T2 => T2,  -- sfix32_En20 [4x4]
              T3 => T3,  -- sfix32_En20 [4x4]
              T4 => T4,  -- sfix32_En20 [4x4]
              T5 => T5,  -- sfix32_En20 [4x4]
              T6 => T6,  -- sfix32_En20 [4x4]
              T7 => T7,  -- sfix32_En20 [4x4]
              T8 => T8,  -- sfix32_En20 [4x4]
              T9 => T9,  -- sfix32_En20 [4x4]
              T10 => T10,  -- sfix32_En20 [4x4]
              T11 => T11,  -- sfix32_En20 [4x4]
              T12 => T12,  -- sfix32_En20 [4x4]
              T13 => T13,  -- sfix32_En20 [4x4]
              T14 => T14,  -- sfix32_En20 [4x4]
              T15 => T15,  -- sfix32_En20 [4x4]
              T16 => T16,  -- sfix32_En20 [4x4]
              S_k_inv => S_k_inv  -- sfix33_En20 [4x4]
              );

  outputgen6: FOR k IN 0 TO 3 GENERATE
    outputgen7: FOR k1 IN 0 TO 3 GENERATE
      P_k_k_1_signed(k, k1) <= signed(P_k_k_1(k, k1));
    END GENERATE;
  END GENERATE;

  s_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_gen: FOR d0 IN 0 TO 3 GENERATE
      s(d0 + (d1 * 4)) <= P_k_k_1_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_gen: FOR ii_select IN 0 TO 63 GENERATE
    selector_out(ii_select) <= s(to_integer(resize(select_indices0_data(ii_select), 32) - 1));
  END GENERATE selector_out_gen;


  s_1_gen: FOR d0 IN 0 TO 63 GENERATE
    s_1(d0) <= selector_out(d0);
  END GENERATE;

  outputgen4: FOR k IN 0 TO 3 GENERATE
    outputgen5: FOR k1 IN 0 TO 3 GENERATE
      H_signed(k, k1) <= signed(H(k, k1));
    END GENERATE;
  END GENERATE;


  Transpose_out1_gen: FOR t_1 IN 0 TO 3 GENERATE
    Transpose_out1_gen_1: FOR t_0 IN 0 TO 3 GENERATE
      Transpose_out1(t_0, t_1) <= H_signed(t_1, t_0);
    END GENERATE Transpose_out1_gen_1;
  END GENERATE Transpose_out1_gen;


  s_2_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_2_gen: FOR d0 IN 0 TO 3 GENERATE
      s_2(d0 + (d1 * 4)) <= Transpose_out1(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_1_gen: FOR ii_select1 IN 0 TO 63 GENERATE
    selector_out_1(ii_select1) <= s_2(to_integer(resize(select_indices1_data(ii_select1), 32) - 1));
  END GENERATE selector_out_1_gen;


  s_3_gen: FOR d0 IN 0 TO 63 GENERATE
    s_3(d0) <= selector_out_1(d0);
  END GENERATE;


  MMul_dot_product_out_gen: FOR t_01 IN 0 TO 63 GENERATE
    MMul_dot_product_out(t_01) <= s_1(t_01) * s_3(t_01);
  END GENERATE MMul_dot_product_out_gen;


  reshape_out_gen1: FOR d1 IN 0 TO 15 GENERATE
    reshape_out_gen: FOR d0 IN 0 TO 3 GENERATE
      reshape_out(d0, d1) <= MMul_dot_product_out(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;


  selector_out_2_gen: FOR t_02 IN 0 TO 15 GENERATE
    selector_out_2(t_02) <= reshape_out(0, t_02);
  END GENERATE selector_out_2_gen;



  selector_out_3_gen: FOR t_03 IN 0 TO 15 GENERATE
    selector_out_3(t_03) <= reshape_out(1, t_03);
  END GENERATE selector_out_3_gen;



  MMul_add_01_out_gen: FOR t_04 IN 0 TO 15 GENERATE
    MMul_add_01_out(t_04) <= selector_out_2(t_04) + selector_out_3(t_04);
  END GENERATE MMul_add_01_out_gen;



  selector_out_4_gen: FOR t_05 IN 0 TO 15 GENERATE
    selector_out_4(t_05) <= reshape_out(2, t_05);
  END GENERATE selector_out_4_gen;



  MMul_add_12_out_gen: FOR t_06 IN 0 TO 15 GENERATE
    MMul_add_12_out(t_06) <= MMul_add_01_out(t_06) + selector_out_4(t_06);
  END GENERATE MMul_add_12_out_gen;



  selector_out_5_gen: FOR t_07 IN 0 TO 15 GENERATE
    selector_out_5(t_07) <= reshape_out(3, t_07);
  END GENERATE selector_out_5_gen;



  s_4_gen: FOR t_08 IN 0 TO 15 GENERATE
    s_4(t_08) <= MMul_add_12_out(t_08) + selector_out_5(t_08);
  END GENERATE s_4_gen;



  selector_out_6_gen: FOR ii_select2 IN 0 TO 63 GENERATE
    selector_out_6(ii_select2) <= s_4(to_integer(resize(select_indices01_data(ii_select2), 32) - 1));
  END GENERATE selector_out_6_gen;


  s_5_gen: FOR d0 IN 0 TO 63 GENERATE
    s_5(d0) <= selector_out_6(d0);
  END GENERATE;

  outputgen2: FOR k IN 0 TO 3 GENERATE
    outputgen3: FOR k1 IN 0 TO 3 GENERATE
      S_k_inv_signed(k, k1) <= signed(S_k_inv(k, k1));
    END GENERATE;
  END GENERATE;

  c13_S_k_inv_gen1: FOR d1 IN 0 TO 3 GENERATE
    c13_S_k_inv_gen: FOR d0 IN 0 TO 3 GENERATE
      c13_S_k_inv(d0 + (d1 * 4)) <= S_k_inv_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  c13_Data_Type_Conversion1_out1_gen: FOR ii IN 0 TO 15 GENERATE
    c13_Data_Type_Conversion1_out1(ii) <= c13_S_k_inv(ii)(31 DOWNTO 0);
  END GENERATE c13_Data_Type_Conversion1_out1_gen;


  Data_Type_Conversion1_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Data_Type_Conversion1_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Data_Type_Conversion1_out1(d0, d1) <= c13_Data_Type_Conversion1_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  s_6_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_6_gen: FOR d0 IN 0 TO 3 GENERATE
      s_6(d0 + (d1 * 4)) <= Data_Type_Conversion1_out1(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_7_gen: FOR ii_select3 IN 0 TO 63 GENERATE
    selector_out_7(ii_select3) <= s_6(to_integer(resize(select_indices11_data(ii_select3), 32) - 1));
  END GENERATE selector_out_7_gen;


  s_7_gen: FOR d0 IN 0 TO 63 GENERATE
    s_7(d0) <= selector_out_7(d0);
  END GENERATE;


  MMul_dot_product_out_1_gen: FOR t_09 IN 0 TO 63 GENERATE
    MMul_dot_product_out_1(t_09) <= s_5(t_09) * s_7(t_09);
  END GENERATE MMul_dot_product_out_1_gen;


  reshape_out_1_gen1: FOR d1 IN 0 TO 15 GENERATE
    reshape_out_1_gen: FOR d0 IN 0 TO 3 GENERATE
      reshape_out_1(d0, d1) <= MMul_dot_product_out_1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;


  selector_out_8_gen: FOR t_010 IN 0 TO 15 GENERATE
    selector_out_8(t_010) <= reshape_out_1(0, t_010);
  END GENERATE selector_out_8_gen;



  selector_out_9_gen: FOR t_011 IN 0 TO 15 GENERATE
    selector_out_9(t_011) <= reshape_out_1(1, t_011);
  END GENERATE selector_out_9_gen;



  MMul_add_01_out_1_gen: FOR t_012 IN 0 TO 15 GENERATE
    MMul_add_01_out_1(t_012) <= selector_out_8(t_012) + selector_out_9(t_012);
  END GENERATE MMul_add_01_out_1_gen;



  selector_out_10_gen: FOR t_013 IN 0 TO 15 GENERATE
    selector_out_10(t_013) <= reshape_out_1(2, t_013);
  END GENERATE selector_out_10_gen;



  MMul_add_12_out_1_gen: FOR t_014 IN 0 TO 15 GENERATE
    MMul_add_12_out_1(t_014) <= MMul_add_01_out_1(t_014) + selector_out_10(t_014);
  END GENERATE MMul_add_12_out_1_gen;



  selector_out_11_gen: FOR t_015 IN 0 TO 15 GENERATE
    selector_out_11(t_015) <= reshape_out_1(3, t_015);
  END GENERATE selector_out_11_gen;



  s_8_gen: FOR t_016 IN 0 TO 15 GENERATE
    s_8(t_016) <= MMul_add_12_out_1(t_016) + selector_out_11(t_016);
  END GENERATE s_8_gen;


  Product2_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Product2_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Product2_out1(d0, d1) <= s_8(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c15_Product2_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c15_Product2_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c15_Product2_out1(d0 + (d1 * 4)) <= Product2_out1(d0, d1);
    END GENERATE;
  END GENERATE;


  c15_Data_Type_Conversion2_out1_gen: FOR ii1 IN 0 TO 15 GENERATE
    c15_Data_Type_Conversion2_out1(ii1) <= c15_Product2_out1(ii1)(71 DOWNTO 40);
  END GENERATE c15_Data_Type_Conversion2_out1_gen;


  Data_Type_Conversion2_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Data_Type_Conversion2_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Data_Type_Conversion2_out1(d0, d1) <= c15_Data_Type_Conversion2_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen: FOR k IN 0 TO 3 GENERATE
    outputgen1: FOR k1 IN 0 TO 3 GENERATE
      K_k(k, k1) <= std_logic_vector(Data_Type_Conversion2_out1(k, k1));
    END GENERATE;
  END GENERATE;

END rtl;

