-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\kalman_ac_sim\Kalman_DUT_pkg.vhd
-- Created: 2026-01-10 22:53:45
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Kalman_DUT_pkg IS
  TYPE vector_of_std_logic_vector32 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(31 DOWNTO 0);
  TYPE matrix_of_std_logic_vector32 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF std_logic_vector(31 DOWNTO 0);
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
  TYPE vector_of_signed64 IS ARRAY (NATURAL RANGE <>) OF signed(63 DOWNTO 0);
  TYPE matrix_of_signed64 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(63 DOWNTO 0);
  TYPE matrix_of_std_logic_vector33 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF std_logic_vector(32 DOWNTO 0);
  TYPE matrix_of_signed33 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(32 DOWNTO 0);
  TYPE matrix_of_signed32 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(31 DOWNTO 0);
  TYPE matrix_of_signed67 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(66 DOWNTO 0);
  TYPE vector_of_signed33 IS ARRAY (NATURAL RANGE <>) OF signed(32 DOWNTO 0);
  TYPE vector_of_signed96 IS ARRAY (NATURAL RANGE <>) OF signed(95 DOWNTO 0);
  TYPE matrix_of_signed96 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(95 DOWNTO 0);
  TYPE vector_of_signed8 IS ARRAY (NATURAL RANGE <>) OF signed(7 DOWNTO 0);
END Kalman_DUT_pkg;

