-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\kalman_ac_sim\New_Innovation.vhd
-- Created: 2026-01-10 22:53:45
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: New_Innovation
-- Source Path: kalman_ac_sim/Kalman DUT/New Innovation
-- Hierarchy Level: 1
-- Model version: 1.65
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Kalman_DUT_pkg.ALL;

ENTITY New_Innovation IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        x_k_k                             :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
        z_k                               :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
        H                                 :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        y_k_k                             :   OUT   vector_of_std_logic_vector32(0 TO 3)  -- sfix32_En20 [4]
        );
END New_Innovation;


ARCHITECTURE rtl OF New_Innovation IS

  -- Constants
  CONSTANT select_indices0_data           : vector_of_signed8(0 TO 15) := 
    (to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8),
     to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8),
     to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8),
     to_signed(16#10#, 8));  -- int8 [16]
  CONSTANT select_indices1_data           : vector_of_signed8(0 TO 15) := 
    (to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8),
     to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8),
     to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8),
     to_signed(16#04#, 8));  -- int8 [16]

  -- Signals
  SIGNAL z_k_signed                       : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL H_signed                         : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL s                                : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out                     : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL s_1                              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL x_k_k_signed                     : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL selector_out_1                   : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL s_2                              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL MMul_dot_product_out             : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL reshape_out                      : matrix_of_signed64(0 TO 3, 0 TO 3);  -- sfix64_En40 [4x4]
  SIGNAL selector_out_2                   : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL selector_out_3                   : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL MMul_add_01_out                  : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL selector_out_4                   : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL MMul_add_12_out                  : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL delayMatch_reg                   : vector_of_signed32(0 TO 7);  -- sfix32 [8]
  SIGNAL z_k_1                            : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL selector_out_5                   : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL s_3                              : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL Matrix_Multiply_out1             : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL Add_sub_cast                     : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL Add_out1                         : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL Data_Type_Conversion_out1        : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]

BEGIN
  outputgen4: FOR k IN 0 TO 3 GENERATE
    z_k_signed(k) <= signed(z_k(k));
  END GENERATE;

  outputgen2: FOR k IN 0 TO 3 GENERATE
    outputgen3: FOR k1 IN 0 TO 3 GENERATE
      H_signed(k, k1) <= signed(H(k, k1));
    END GENERATE;
  END GENERATE;

  s_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_gen: FOR d0 IN 0 TO 3 GENERATE
      s(d0 + (d1 * 4)) <= H_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_gen: FOR ii_select IN 0 TO 15 GENERATE
    selector_out(ii_select) <= s(to_integer(resize(select_indices0_data(ii_select), 32) - 1));
  END GENERATE selector_out_gen;


  s_1_gen: FOR d0 IN 0 TO 15 GENERATE
    s_1(d0) <= selector_out(d0);
  END GENERATE;

  outputgen1: FOR k IN 0 TO 3 GENERATE
    x_k_k_signed(k) <= signed(x_k_k(k));
  END GENERATE;


  selector_out_1_gen: FOR ii_select1 IN 0 TO 15 GENERATE
    selector_out_1(ii_select1) <= x_k_k_signed(to_integer(resize(select_indices1_data(ii_select1), 32) - 1));
  END GENERATE selector_out_1_gen;


  s_2_gen: FOR d0 IN 0 TO 15 GENERATE
    s_2(d0) <= selector_out_1(d0);
  END GENERATE;


  MMul_dot_product_out_gen: FOR t_0 IN 0 TO 15 GENERATE
    MMul_dot_product_out(t_0) <= s_1(t_0) * s_2(t_0);
  END GENERATE MMul_dot_product_out_gen;


  reshape_out_gen1: FOR d1 IN 0 TO 3 GENERATE
    reshape_out_gen: FOR d0 IN 0 TO 3 GENERATE
      reshape_out(d0, d1) <= MMul_dot_product_out(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;


  selector_out_2_gen: FOR t_01 IN 0 TO 3 GENERATE
    selector_out_2(t_01) <= reshape_out(0, t_01);
  END GENERATE selector_out_2_gen;



  selector_out_3_gen: FOR t_02 IN 0 TO 3 GENERATE
    selector_out_3(t_02) <= reshape_out(1, t_02);
  END GENERATE selector_out_3_gen;



  MMul_add_01_out_gen: FOR t_03 IN 0 TO 3 GENERATE
    MMul_add_01_out(t_03) <= selector_out_2(t_03) + selector_out_3(t_03);
  END GENERATE MMul_add_01_out_gen;



  selector_out_4_gen: FOR t_04 IN 0 TO 3 GENERATE
    selector_out_4(t_04) <= reshape_out(2, t_04);
  END GENERATE selector_out_4_gen;



  MMul_add_12_out_gen: FOR t_05 IN 0 TO 3 GENERATE
    MMul_add_12_out(t_05) <= MMul_add_01_out(t_05) + selector_out_4(t_05);
  END GENERATE MMul_add_12_out_gen;


  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg(0 TO 3) <= z_k_signed(0 TO 3);
        delayMatch_reg(4 TO 7) <= delayMatch_reg(0 TO 3);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  z_k_1(0 TO 3) <= delayMatch_reg(4 TO 7);


  selector_out_5_gen: FOR t_06 IN 0 TO 3 GENERATE
    selector_out_5(t_06) <= reshape_out(3, t_06);
  END GENERATE selector_out_5_gen;



  s_3_gen: FOR t_07 IN 0 TO 3 GENERATE
    s_3(t_07) <= MMul_add_12_out(t_07) + selector_out_5(t_07);
  END GENERATE s_3_gen;


  Matrix_Multiply_out1_gen: FOR d0 IN 0 TO 3 GENERATE
    Matrix_Multiply_out1(d0) <= s_3(d0);
  END GENERATE;


  Add_out1_gen: FOR t_08 IN 0 TO 3 GENERATE
    Add_sub_cast(t_08) <= resize(z_k_1(t_08) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);
    Add_out1(t_08) <= Add_sub_cast(t_08) - Matrix_Multiply_out1(t_08);
  END GENERATE Add_out1_gen;



  Data_Type_Conversion_out1_gen: FOR ii IN 0 TO 3 GENERATE
    Data_Type_Conversion_out1(ii) <= Add_out1(ii)(51 DOWNTO 20);
  END GENERATE Data_Type_Conversion_out1_gen;


  outputgen: FOR k IN 0 TO 3 GENERATE
    y_k_k(k) <= std_logic_vector(Data_Type_Conversion_out1(k));
  END GENERATE;

END rtl;

