-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\kalman_ac_sim\Update.vhd
-- Created: 2026-01-10 22:53:45
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Update
-- Source Path: kalman_ac_sim/Kalman DUT/Update
-- Hierarchy Level: 1
-- Model version: 1.65
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Kalman_DUT_pkg.ALL;

ENTITY Update IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        x_k_k_1                           :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
        P_k_k_1                           :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        y_k                               :   IN    vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
        K_k                               :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        H                                 :   IN    matrix_of_std_logic_vector32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
        x_k_k                             :   OUT   vector_of_std_logic_vector32(0 TO 3);  -- sfix32_En20 [4]
        P_k_k                             :   OUT   matrix_of_std_logic_vector32(0 TO 3, 0 TO 3)  -- sfix32_En20 [4x4]
        );
END Update;


ARCHITECTURE rtl OF Update IS

  -- Constants
  CONSTANT select_indices0_data           : vector_of_signed8(0 TO 15) := 
    (to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8),
     to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8),
     to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8),
     to_signed(16#10#, 8));  -- int8 [16]
  CONSTANT select_indices1_data           : vector_of_signed8(0 TO 15) := 
    (to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8),
     to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8),
     to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8),
     to_signed(16#04#, 8));  -- int8 [16]
  CONSTANT select_indices01_data          : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8),
     to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8),
     to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8),
     to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8),
     to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8),
     to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8),
     to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8),
     to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8),
     to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8),
     to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8),
     to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8),
     to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8),
     to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8));  -- int8 [64]
  CONSTANT select_indices11_data          : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8),
     to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8),
     to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8),
     to_signed(16#04#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8),
     to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8),
     to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8),
     to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8),
     to_signed(16#0C#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8),
     to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#09#, 8),
     to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8),
     to_signed(16#0F#, 8), to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8),
     to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8),
     to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8));  -- int8 [64]
  CONSTANT select_indices02_data          : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8),
     to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8),
     to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8),
     to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8), to_signed(16#0D#, 8),
     to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8), to_signed(16#03#, 8),
     to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8), to_signed(16#08#, 8),
     to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8), to_signed(16#09#, 8),
     to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8), to_signed(16#0E#, 8),
     to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8), to_signed(16#04#, 8),
     to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8), to_signed(16#01#, 8), to_signed(16#05#, 8),
     to_signed(16#09#, 8), to_signed(16#0D#, 8), to_signed(16#02#, 8), to_signed(16#06#, 8), to_signed(16#0A#, 8),
     to_signed(16#0E#, 8), to_signed(16#03#, 8), to_signed(16#07#, 8), to_signed(16#0B#, 8), to_signed(16#0F#, 8),
     to_signed(16#04#, 8), to_signed(16#08#, 8), to_signed(16#0C#, 8), to_signed(16#10#, 8));  -- int8 [64]
  CONSTANT select_indices12_data          : vector_of_signed8(0 TO 63) := 
    (to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8),
     to_signed(16#02#, 8), to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8),
     to_signed(16#03#, 8), to_signed(16#04#, 8), to_signed(16#01#, 8), to_signed(16#02#, 8), to_signed(16#03#, 8),
     to_signed(16#04#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8),
     to_signed(16#05#, 8), to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8),
     to_signed(16#06#, 8), to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#05#, 8), to_signed(16#06#, 8),
     to_signed(16#07#, 8), to_signed(16#08#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8),
     to_signed(16#0C#, 8), to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8),
     to_signed(16#09#, 8), to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#09#, 8),
     to_signed(16#0A#, 8), to_signed(16#0B#, 8), to_signed(16#0C#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8),
     to_signed(16#0F#, 8), to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8),
     to_signed(16#10#, 8), to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8),
     to_signed(16#0D#, 8), to_signed(16#0E#, 8), to_signed(16#0F#, 8), to_signed(16#10#, 8));  -- int8 [64]

  -- Signals
  SIGNAL K_k_signed                       : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL s                                : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out                     : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL s_1                              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL delayMatch_reg                   : vector_of_signed32(0 TO 31);  -- sfix32 [32]
  SIGNAL s_2                              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL y_k_signed                       : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL selector_out_1                   : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL s_3                              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL MMul_dot_product_out             : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL reshape_out                      : matrix_of_signed64(0 TO 3, 0 TO 3);  -- sfix64_En40 [4x4]
  SIGNAL selector_out_2                   : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL selector_out_3                   : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL MMul_add_01_out                  : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL selector_out_4                   : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL MMul_add_12_out                  : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL selector_out_5                   : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL s_4                              : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL Product_out1                     : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL x_k_k_1_signed                   : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL Add_add_cast                     : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL Add_out1                         : vector_of_signed64(0 TO 3);  -- sfix64_En40 [4]
  SIGNAL Data_Type_Conversion2_out1       : vector_of_signed32(0 TO 3);  -- sfix32_En20 [4]
  SIGNAL K_k_signed_1                     : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL s_5                              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out_6                   : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL s_6                              : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL H_signed                         : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL s_7                              : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out_7                   : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL s_8                              : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL MMul_dot_product_out_1           : vector_of_signed64(0 TO 63);  -- sfix64_En40 [64]
  SIGNAL reshape_out_1                    : matrix_of_signed64(0 TO 3, 0 TO 15);  -- sfix64_En40 [4x16]
  SIGNAL selector_out_8                   : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL selector_out_9                   : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL MMul_add_01_out_1                : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL selector_out_10                  : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL MMul_add_12_out_1                : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL c9_Constant_out1                 : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out_11                  : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL s_9                              : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL Product1_out1                    : matrix_of_signed64(0 TO 3, 0 TO 3);  -- sfix64_En40 [4x4]
  SIGNAL c20_Product1_out1                : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL Add1_sub_cast                    : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL c20_Add1_out1                    : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL Add1_out1                        : matrix_of_signed64(0 TO 3, 0 TO 3);  -- sfix64_En40 [4x4]
  SIGNAL s_10                             : vector_of_signed64(0 TO 15);  -- sfix64_En40 [16]
  SIGNAL selector_out_12                  : vector_of_signed64(0 TO 63);  -- sfix64_En40 [64]
  SIGNAL s_11                             : vector_of_signed64(0 TO 63);  -- sfix64_En40 [64]
  SIGNAL P_k_k_1_signed                   : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]
  SIGNAL s_12                             : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL selector_out_13                  : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL s_13                             : vector_of_signed32(0 TO 63);  -- sfix32_En20 [64]
  SIGNAL MMul_dot_product_out_2           : vector_of_signed96(0 TO 63);  -- sfix96_En60 [64]
  SIGNAL reshape_out_2                    : matrix_of_signed96(0 TO 3, 0 TO 15);  -- sfix96_En60 [4x16]
  SIGNAL selector_out_14                  : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL selector_out_15                  : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL MMul_add_01_out_2                : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL selector_out_16                  : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL MMul_add_12_out_2                : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL selector_out_17                  : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL s_14                             : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL Product2_out1                    : matrix_of_signed96(0 TO 3, 0 TO 3);  -- sfix96_En60 [4x4]
  SIGNAL c22_Product2_out1                : vector_of_signed96(0 TO 15);  -- sfix96_En60 [16]
  SIGNAL c22_Data_Type_Conversion_out1    : vector_of_signed32(0 TO 15);  -- sfix32_En20 [16]
  SIGNAL Data_Type_Conversion_out1        : matrix_of_signed32(0 TO 3, 0 TO 3);  -- sfix32_En20 [4x4]

BEGIN
  outputgen11: FOR k IN 0 TO 3 GENERATE
    outputgen12: FOR k1 IN 0 TO 3 GENERATE
      K_k_signed(k, k1) <= signed(K_k(k, k1));
    END GENERATE;
  END GENERATE;

  s_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_gen: FOR d0 IN 0 TO 3 GENERATE
      s(d0 + (d1 * 4)) <= K_k_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_gen: FOR ii_select IN 0 TO 15 GENERATE
    selector_out(ii_select) <= s(to_integer(resize(select_indices0_data(ii_select), 32) - 1));
  END GENERATE selector_out_gen;


  s_1_gen: FOR d0 IN 0 TO 15 GENERATE
    s_1(d0) <= selector_out(d0);
  END GENERATE;

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg(0 TO 15) <= s_1(0 TO 15);
        delayMatch_reg(16 TO 31) <= delayMatch_reg(0 TO 15);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  s_2(0 TO 15) <= delayMatch_reg(16 TO 31);

  outputgen10: FOR k IN 0 TO 3 GENERATE
    y_k_signed(k) <= signed(y_k(k));
  END GENERATE;


  selector_out_1_gen: FOR ii_select1 IN 0 TO 15 GENERATE
    selector_out_1(ii_select1) <= y_k_signed(to_integer(resize(select_indices1_data(ii_select1), 32) - 1));
  END GENERATE selector_out_1_gen;


  s_3_gen: FOR d0 IN 0 TO 15 GENERATE
    s_3(d0) <= selector_out_1(d0);
  END GENERATE;


  MMul_dot_product_out_gen: FOR t_0 IN 0 TO 15 GENERATE
    MMul_dot_product_out(t_0) <= s_2(t_0) * s_3(t_0);
  END GENERATE MMul_dot_product_out_gen;


  reshape_out_gen1: FOR d1 IN 0 TO 3 GENERATE
    reshape_out_gen: FOR d0 IN 0 TO 3 GENERATE
      reshape_out(d0, d1) <= MMul_dot_product_out(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;


  selector_out_2_gen: FOR t_01 IN 0 TO 3 GENERATE
    selector_out_2(t_01) <= reshape_out(0, t_01);
  END GENERATE selector_out_2_gen;



  selector_out_3_gen: FOR t_02 IN 0 TO 3 GENERATE
    selector_out_3(t_02) <= reshape_out(1, t_02);
  END GENERATE selector_out_3_gen;



  MMul_add_01_out_gen: FOR t_03 IN 0 TO 3 GENERATE
    MMul_add_01_out(t_03) <= selector_out_2(t_03) + selector_out_3(t_03);
  END GENERATE MMul_add_01_out_gen;



  selector_out_4_gen: FOR t_04 IN 0 TO 3 GENERATE
    selector_out_4(t_04) <= reshape_out(2, t_04);
  END GENERATE selector_out_4_gen;



  MMul_add_12_out_gen: FOR t_05 IN 0 TO 3 GENERATE
    MMul_add_12_out(t_05) <= MMul_add_01_out(t_05) + selector_out_4(t_05);
  END GENERATE MMul_add_12_out_gen;



  selector_out_5_gen: FOR t_06 IN 0 TO 3 GENERATE
    selector_out_5(t_06) <= reshape_out(3, t_06);
  END GENERATE selector_out_5_gen;



  s_4_gen: FOR t_07 IN 0 TO 3 GENERATE
    s_4(t_07) <= MMul_add_12_out(t_07) + selector_out_5(t_07);
  END GENERATE s_4_gen;


  Product_out1_gen: FOR d0 IN 0 TO 3 GENERATE
    Product_out1(d0) <= s_4(d0);
  END GENERATE;

  outputgen9: FOR k IN 0 TO 3 GENERATE
    x_k_k_1_signed(k) <= signed(x_k_k_1(k));
  END GENERATE;


  Add_out1_gen: FOR t_08 IN 0 TO 3 GENERATE
    Add_add_cast(t_08) <= resize(x_k_k_1_signed(t_08) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);
    Add_out1(t_08) <= Product_out1(t_08) + Add_add_cast(t_08);
  END GENERATE Add_out1_gen;



  Data_Type_Conversion2_out1_gen: FOR ii IN 0 TO 3 GENERATE
    Data_Type_Conversion2_out1(ii) <= Add_out1(ii)(51 DOWNTO 20);
  END GENERATE Data_Type_Conversion2_out1_gen;


  outputgen8: FOR k IN 0 TO 3 GENERATE
    x_k_k(k) <= std_logic_vector(Data_Type_Conversion2_out1(k));
  END GENERATE;

  outputgen6: FOR k IN 0 TO 3 GENERATE
    outputgen7: FOR k1 IN 0 TO 3 GENERATE
      K_k_signed_1(k, k1) <= signed(K_k(k, k1));
    END GENERATE;
  END GENERATE;

  s_5_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_5_gen: FOR d0 IN 0 TO 3 GENERATE
      s_5(d0 + (d1 * 4)) <= K_k_signed_1(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_6_gen: FOR ii_select2 IN 0 TO 63 GENERATE
    selector_out_6(ii_select2) <= s_5(to_integer(resize(select_indices01_data(ii_select2), 32) - 1));
  END GENERATE selector_out_6_gen;


  s_6_gen: FOR d0 IN 0 TO 63 GENERATE
    s_6(d0) <= selector_out_6(d0);
  END GENERATE;

  outputgen4: FOR k IN 0 TO 3 GENERATE
    outputgen5: FOR k1 IN 0 TO 3 GENERATE
      H_signed(k, k1) <= signed(H(k, k1));
    END GENERATE;
  END GENERATE;

  s_7_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_7_gen: FOR d0 IN 0 TO 3 GENERATE
      s_7(d0 + (d1 * 4)) <= H_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_7_gen: FOR ii_select3 IN 0 TO 63 GENERATE
    selector_out_7(ii_select3) <= s_7(to_integer(resize(select_indices11_data(ii_select3), 32) - 1));
  END GENERATE selector_out_7_gen;


  s_8_gen: FOR d0 IN 0 TO 63 GENERATE
    s_8(d0) <= selector_out_7(d0);
  END GENERATE;


  MMul_dot_product_out_1_gen: FOR t_09 IN 0 TO 63 GENERATE
    MMul_dot_product_out_1(t_09) <= s_6(t_09) * s_8(t_09);
  END GENERATE MMul_dot_product_out_1_gen;


  reshape_out_1_gen1: FOR d1 IN 0 TO 15 GENERATE
    reshape_out_1_gen: FOR d0 IN 0 TO 3 GENERATE
      reshape_out_1(d0, d1) <= MMul_dot_product_out_1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;


  selector_out_8_gen: FOR t_010 IN 0 TO 15 GENERATE
    selector_out_8(t_010) <= reshape_out_1(0, t_010);
  END GENERATE selector_out_8_gen;



  selector_out_9_gen: FOR t_011 IN 0 TO 15 GENERATE
    selector_out_9(t_011) <= reshape_out_1(1, t_011);
  END GENERATE selector_out_9_gen;



  MMul_add_01_out_1_gen: FOR t_012 IN 0 TO 15 GENERATE
    MMul_add_01_out_1(t_012) <= selector_out_8(t_012) + selector_out_9(t_012);
  END GENERATE MMul_add_01_out_1_gen;



  selector_out_10_gen: FOR t_013 IN 0 TO 15 GENERATE
    selector_out_10(t_013) <= reshape_out_1(2, t_013);
  END GENERATE selector_out_10_gen;



  MMul_add_12_out_1_gen: FOR t_014 IN 0 TO 15 GENERATE
    MMul_add_12_out_1(t_014) <= MMul_add_01_out_1(t_014) + selector_out_10(t_014);
  END GENERATE MMul_add_12_out_1_gen;


  c9_Constant_out1(0) <= to_signed(1048576, 32);
  c9_Constant_out1(1) <= to_signed(0, 32);
  c9_Constant_out1(2) <= to_signed(0, 32);
  c9_Constant_out1(3) <= to_signed(0, 32);
  c9_Constant_out1(4) <= to_signed(0, 32);
  c9_Constant_out1(5) <= to_signed(1048576, 32);
  c9_Constant_out1(6) <= to_signed(0, 32);
  c9_Constant_out1(7) <= to_signed(0, 32);
  c9_Constant_out1(8) <= to_signed(0, 32);
  c9_Constant_out1(9) <= to_signed(0, 32);
  c9_Constant_out1(10) <= to_signed(1048576, 32);
  c9_Constant_out1(11) <= to_signed(0, 32);
  c9_Constant_out1(12) <= to_signed(0, 32);
  c9_Constant_out1(13) <= to_signed(0, 32);
  c9_Constant_out1(14) <= to_signed(0, 32);
  c9_Constant_out1(15) <= to_signed(1048576, 32);


  selector_out_11_gen: FOR t_015 IN 0 TO 15 GENERATE
    selector_out_11(t_015) <= reshape_out_1(3, t_015);
  END GENERATE selector_out_11_gen;



  s_9_gen: FOR t_016 IN 0 TO 15 GENERATE
    s_9(t_016) <= MMul_add_12_out_1(t_016) + selector_out_11(t_016);
  END GENERATE s_9_gen;


  Product1_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Product1_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Product1_out1(d0, d1) <= s_9(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c20_Product1_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c20_Product1_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c20_Product1_out1(d0 + (d1 * 4)) <= Product1_out1(d0, d1);
    END GENERATE;
  END GENERATE;


  c20_Add1_out1_gen: FOR t_017 IN 0 TO 15 GENERATE
    Add1_sub_cast(t_017) <= resize(c9_Constant_out1(t_017) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);
    c20_Add1_out1(t_017) <= Add1_sub_cast(t_017) - c20_Product1_out1(t_017);
  END GENERATE c20_Add1_out1_gen;


  Add1_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Add1_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Add1_out1(d0, d1) <= c20_Add1_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  s_10_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_10_gen: FOR d0 IN 0 TO 3 GENERATE
      s_10(d0 + (d1 * 4)) <= Add1_out1(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_12_gen: FOR ii_select4 IN 0 TO 63 GENERATE
    selector_out_12(ii_select4) <= s_10(to_integer(resize(select_indices02_data(ii_select4), 32) - 1));
  END GENERATE selector_out_12_gen;


  s_11_gen: FOR d0 IN 0 TO 63 GENERATE
    s_11(d0) <= selector_out_12(d0);
  END GENERATE;

  outputgen2: FOR k IN 0 TO 3 GENERATE
    outputgen3: FOR k1 IN 0 TO 3 GENERATE
      P_k_k_1_signed(k, k1) <= signed(P_k_k_1(k, k1));
    END GENERATE;
  END GENERATE;

  s_12_gen1: FOR d1 IN 0 TO 3 GENERATE
    s_12_gen: FOR d0 IN 0 TO 3 GENERATE
      s_12(d0 + (d1 * 4)) <= P_k_k_1_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  selector_out_13_gen: FOR ii_select5 IN 0 TO 63 GENERATE
    selector_out_13(ii_select5) <= s_12(to_integer(resize(select_indices12_data(ii_select5), 32) - 1));
  END GENERATE selector_out_13_gen;


  s_13_gen: FOR d0 IN 0 TO 63 GENERATE
    s_13(d0) <= selector_out_13(d0);
  END GENERATE;


  MMul_dot_product_out_2_gen: FOR t_018 IN 0 TO 63 GENERATE
    MMul_dot_product_out_2(t_018) <= s_11(t_018) * s_13(t_018);
  END GENERATE MMul_dot_product_out_2_gen;


  reshape_out_2_gen1: FOR d1 IN 0 TO 15 GENERATE
    reshape_out_2_gen: FOR d0 IN 0 TO 3 GENERATE
      reshape_out_2(d0, d1) <= MMul_dot_product_out_2(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;


  selector_out_14_gen: FOR t_019 IN 0 TO 15 GENERATE
    selector_out_14(t_019) <= reshape_out_2(0, t_019);
  END GENERATE selector_out_14_gen;



  selector_out_15_gen: FOR t_020 IN 0 TO 15 GENERATE
    selector_out_15(t_020) <= reshape_out_2(1, t_020);
  END GENERATE selector_out_15_gen;



  MMul_add_01_out_2_gen: FOR t_021 IN 0 TO 15 GENERATE
    MMul_add_01_out_2(t_021) <= selector_out_14(t_021) + selector_out_15(t_021);
  END GENERATE MMul_add_01_out_2_gen;



  selector_out_16_gen: FOR t_022 IN 0 TO 15 GENERATE
    selector_out_16(t_022) <= reshape_out_2(2, t_022);
  END GENERATE selector_out_16_gen;



  MMul_add_12_out_2_gen: FOR t_023 IN 0 TO 15 GENERATE
    MMul_add_12_out_2(t_023) <= MMul_add_01_out_2(t_023) + selector_out_16(t_023);
  END GENERATE MMul_add_12_out_2_gen;



  selector_out_17_gen: FOR t_024 IN 0 TO 15 GENERATE
    selector_out_17(t_024) <= reshape_out_2(3, t_024);
  END GENERATE selector_out_17_gen;



  s_14_gen: FOR t_025 IN 0 TO 15 GENERATE
    s_14(t_025) <= MMul_add_12_out_2(t_025) + selector_out_17(t_025);
  END GENERATE s_14_gen;


  Product2_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Product2_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Product2_out1(d0, d1) <= s_14(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  c22_Product2_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    c22_Product2_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      c22_Product2_out1(d0 + (d1 * 4)) <= Product2_out1(d0, d1);
    END GENERATE;
  END GENERATE;


  c22_Data_Type_Conversion_out1_gen: FOR ii1 IN 0 TO 15 GENERATE
    c22_Data_Type_Conversion_out1(ii1) <= c22_Product2_out1(ii1)(71 DOWNTO 40);
  END GENERATE c22_Data_Type_Conversion_out1_gen;


  Data_Type_Conversion_out1_gen1: FOR d1 IN 0 TO 3 GENERATE
    Data_Type_Conversion_out1_gen: FOR d0 IN 0 TO 3 GENERATE
      Data_Type_Conversion_out1(d0, d1) <= c22_Data_Type_Conversion_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen: FOR k IN 0 TO 3 GENERATE
    outputgen1: FOR k1 IN 0 TO 3 GENERATE
      P_k_k(k, k1) <= std_logic_vector(Data_Type_Conversion_out1(k, k1));
    END GENERATE;
  END GENERATE;

END rtl;

